# Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import ast
import os

# from IPython.display import display, Markdown
# from pymongo.mongo_client import MongoClient
# from bson.objectid import ObjectId

# %pip install deep-translator
from deep_translator import GoogleTranslator

In [2]:
# Define the directory containing the CSV files
directory = "../csv_backup"

# Initialize an empty list to store DataFrames
dataframes = []

# Loop through all files in the directory
for filename in os.listdir(directory):
    if filename.endswith(".csv"):  # Check if the file is a CSV
        file_path = os.path.join(directory, filename)
        # Read the CSV file into a DataFrame
        df = pd.read_csv(file_path)
        ### DROP DUPLICATES
        df = df.drop_duplicates()
        dataframes.append(df)

# Combine all DataFrames into a single DataFrame (optional)
data = pd.concat(dataframes)
data.head(3)

,ten_cong_viec,ten_cong_ty,muc_luong,dia_chi,ngay_dang,nganh_nghe,quy_mo_cong_ty,quoc_tich_cong_ty,nam_kinh_nghiem,cap_bac,loai_hinh,loai_hop_dong,cong_nghe_su_dung,quy_trinh_phong_van,mo_ta_cong_viec,thong_tin_cong_ty,url,thoi_gian_hien_tai,url_cong_ty
0,['Senior Full-stack Developer'],['CÔNG TY CỔ PHẦN IZOTA'],[],"['20/33a Đồng Xoài, Phường 13, Quận Tân Bình, ...",['Đăng 1 ngày trước'],[''],['Nhân viên'],[''],['Từ 3 năm'],['Senior'],['In Office'],['Fulltime'],"['JavaScript', 'Python', '.NET']",[],['iZOTA focuses on accelerating digital transf...,Về chúng tôi\nChế độ đãi ngộ,https://topdev.vn/viec-lam/senior-full-stack-d...,2024-11-03 21:38:30,https://topdev.vn/vi/nha-tuyen-dung/cong-ty-co...
1,['Chuyên viên Phát triển phần mềm (DEV) – Mã v...,['BIDV - Trung tâm Phát triển ngân hàng số'],['Thương lượng'],"['Tháp A Vincom, 191 Bà Triệu, Phường Lê Đại H...",['Đăng 1 ngày trước'],['Ngân Hàng'],['Hơn 1000 Nhân viên'],['Vietnam'],['Từ 1 năm'],"['Junior, Middle, Senior']",['In Office'],['Fulltime'],"['Java', 'ReactJS', 'Restful Api', 'Flutter', ...","['Vòng 1: Sơ tuyển hồ sơ', 'Vòng 2: Phỏng vấn ...",['Trách nhiệm công việc\nDev Mobile\nXây dựng ...,Về chúng tôi\nNgân hàng TMCP Đầu tư và Phát tr...,https://topdev.vn/viec-lam/chuyen-vien-phat-tr...,2024-11-03 21:38:30,https://topdev.vn/nha-tuyen-dung/bidv-trung-ta...
2,"['[DI6] Solution Architect (Aws, Java)- MSB - ...",['Ngân hàng TMCP Hàng Hải Việt Nam (MSB)'],['2.500 USD to 3.500 USD'],"['TNR Tower, Số 54A Nguyễn Chí Thanh, Phường L...",['Đăng 1 ngày trước'],"['Ngân Hàng, Tài Chính, Công nghệ thông tin']",['Hơn 1000 Nhân viên'],['Vietnam'],['Từ 3 năm'],"['Junior, Senior']",['In Office'],['Fulltime'],"['Java', 'Python', 'AWS', 'Business Intelligen...",[],['Trách nhiệm công việc\n1. Quản trị Kiến trúc...,"Về chúng tôi\nNgay từ khi thành lập, MSB đã gh...",https://topdev.vn/viec-lam/di6-solution-archit...,2024-11-03 21:38:30,https://topdev.vn/nha-tuyen-dung/ngan-hang-tmc...

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12231 entries, 0 to 748
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_cong_viec        12231 non-null  object
 1   ten_cong_ty          12231 non-null  object
 2   muc_luong            12231 non-null  object
 3   dia_chi              12231 non-null  object
 4   ngay_dang            12231 non-null  object
 5   nganh_nghe           12231 non-null  object
 6   quy_mo_cong_ty       12231 non-null  object
 7   quoc_tich_cong_ty    12231 non-null  object
 8   nam_kinh_nghiem      12231 non-null  object
 9   cap_bac              12231 non-null  object
 10  loai_hinh            12231 non-null  object
 11  loai_hop_dong        12231 non-null  object
 12  cong_nghe_su_dung    12231 non-null  object
 13  quy_trinh_phong_van  12231 non-null  object
 14  mo_ta_cong_viec      12231 non-null  object
 15  thong_tin_cong_ty    12219 non-null  object
 16  url                  12231 non-null  object
 17  thoi_gian_hien_tai   12231 non-null  object
 18  url_cong_ty          12231 non-null  object
dtypes: object(19)
memory usage: 1.9+ MB

# Preprocess

In [4]:
data["muc_luong"] = data["muc_luong"].replace("[]", "['Thương lượng']")
data["thoi_gian_hien_tai"] = data["thoi_gian_hien_tai"].apply(pd.to_datetime)
for col in data.columns:
    if col in ["thong_tin_cong_ty", "url", "url_cong_ty", "thoi_gian_hien_tai"]:
        continue
    data[col] = data[col].apply(ast.literal_eval)


def getOnlyElement(series):
    return series[0]


for col in data.columns:
    if col in ["thong_tin_cong_ty", "url", "url_cong_ty", "thoi_gian_hien_tai"]:
        continue
    if col in [
        "dia_chi",
        "loai_hinh",
        "loai_hop_dong",
        "cong_nghe_su_dung",
        "quy_trinh_phong_van",
    ]:
        continue
    data[col] = data[col].apply(getOnlyElement)

In [5]:
def split_(series):
    return series.split(", ")

def castUSA(series):
    return series.replace("USA", "United States")

data["cap_bac"] = data.cap_bac.apply(split_)
data["quoc_tich_cong_ty"] = data.quoc_tich_cong_ty.apply(castUSA).apply(split_)

In [6]:
def split_domain(series):
    lst = series.split(", ")
    if "Phần Mềm" in lst or "Software" in lst:
        lst = [x for x in lst if x!="Phần Mềm" and x!="Software"]   
        lst.append("Phần Mềm")     
    return lst
data["nganh_nghe"] = data.nganh_nghe.apply(split_domain)

In [7]:
def experience(series):
    num = re.findall(r"\d+", series)
    if len(num) == 0:
        return 0
    num = num[0]
    if "tháng" in series:
        return int(num) * 1.0 / 12
    if "năm" in series:
        return int(num)
    return pd.NA


data["nam_kinh_nghiem"] = data.nam_kinh_nghiem.apply(experience)

In [8]:
def size(series):
    if "." in series:
        series = series.replace(".", "")
    num = re.findall(r"\d+", series)
    if len(num) == 0:
        return None
    res = int(num[0])
    if res < 100:
        return "Nhỏ"
    if res < 1000:
        return "Vừa"
    return "Lớn"

data["so_luong_nhan_vien"] = data.quy_mo_cong_ty
data["quy_mo_cong_ty"] = data.quy_mo_cong_ty.apply(size)

In [9]:
def n_number(series):
    if "." in series:
        series = series.replace(".", "")
    num = re.findall(r"\d+", series)
    if len(num) == 0:
        return [0, 2000000]
    if len(num) == 1:
        return [int(num[0]), 2000000]
    return [int(num[0]), int(num[1])]

data["so_luong_nhan_vien"] = data.so_luong_nhan_vien.apply(n_number)

In [10]:
def extract_salary_range(salary):
    if salary == "Thương lượng":
        return [0, 0]
    numbers = re.findall(r"[\d.,]+", salary)
    if numbers:
        numbers = [float(num.replace(".", "").strip()) for num in numbers]
        if len(numbers) == 1:
            if numbers[0] > 1_000_000:
                numbers[0] = numbers[0] / 24_000
            return [0, round(numbers[0], 2)]
        for i in range(len(numbers)):
            if numbers[i] > 1_000_000:
                numbers[i] = numbers[i] / 24_000

        # Lấy giá trị nhỏ nhất và lớn nhất
        min_value = min(numbers)
        max_value = max(numbers)

        return [round(min_value, 2), round(max_value, 2)]
    return [0, 0]


data["muc_luong"] = data["muc_luong"].apply(extract_salary_range)

In [11]:
data.replace("", pd.NA, inplace=True)
data.replace(pd.NA, "Khong co thong tin", inplace=True)

## Translate the job title into English

In [12]:
# 2. Hàm dịch tự động sử dụng Deep Translator
def translate_to_english(text):
    try:
        # Sử dụng Google Translate qua Deep Translator
        translated = text
        translated = GoogleTranslator(source='auto', target='en').translate(text)
        return translated
    except Exception as e:
        print(f"Translation failed for: {text}, Error: {e}")
        return text  # Trả về văn bản gốc nếu dịch lỗi
map_data = data.ten_cong_viec.value_counts().to_frame().reset_index().drop(columns=["count"])
vectorized_func = np.vectorize(translate_to_english)
map_res = vectorized_func(map_data["ten_cong_viec"].to_numpy())

In [13]:
map_data["translated"] = map_res
map_data = map_data.set_index("ten_cong_viec")
map_dict = map_data["translated"].to_dict()

In [14]:
def map_translate_result(text):
    try:
        return map_dict[text]
    except:
        print("Error mapping")
        return ""

# 6. Áp dụng hàm vào cột "Job Title"
data['ten_cong_viec'] = data['ten_cong_viec'].apply(map_translate_result)

# 7. In kết quả
data['ten_cong_viec']

0                            Senior Full-stack Developer
1      Software Development Specialist (DEV) – Positi...
2      [DI6] Solution Architect (Aws, Java)- MSB - 1Y564
3                       Manager (JLPT N2, Sign-on Bonus)
4               Backend Developer (Java, Python, NodeJS)
                             ...
744                       Back-End Developer (Java, SQL)
745                                        AI Researcher
746                             Backend Developer (Java)
747                            DATA ARCHITECT SPECIALIST
748                   Windows Technical Support Engineer
Name: ten_cong_viec, Length: 12231, dtype: object

## Cluster the jobs from job titles

In [15]:
# Reusing job group keywords for classification
job_groups = {
    "Management": ["manager", "lead", "coordinator", "scrum", "product owner","administrator","management"],
    "Software/Web/Mobile Development": ["programmer", "coder", "software","web","frontend","backend","game","development","fullstack","dev", "mobile", "ios", "android", "flutter", "react native"],
    "Data & AI": ["data", "ml", "machine learning", "big data", "scientist","ai engineer","ai technical"],
    "Business Analysis":["business analyst","business analysis","business system analyst"],
    "IT Solution & Consulting":["solution","consultant"],
    "QA & Testing": ["qa", "test", "testing", "automation","assurance"],
    "Infrastructure & DevOps": ["devops", "cloud", "system", "administrator", "infrastructure","architect"],
    "Cybersecurity": ["security", "cyber", "pen tester", "forensic", "vulnerability"],
    "Design & UI/UX": ["designer", "ui", "ux", "graphic", "product designer","2D","3D"],
    "Support": ["support", "helpdesk", "service desk"],
    "Other": []
}

# Classify jobs into groups based on keywords
def classify_job(title):
    title_lower = title.lower()
    matched_groups = []
    for group, keywords in job_groups.items():
        if any(keyword in title_lower for keyword in keywords):
            matched_groups.append(group)
    return matched_groups if matched_groups else ["Other"]

job_titles_sample = data["ten_cong_viec"]
# Apply classification to the sample titles
classified_jobs = {title: classify_job(title) for title in job_titles_sample}
data["nhom_cong_viec"] = classified_jobs

In [16]:
data["nhom_cong_viec"] = data["ten_cong_viec"].apply(classify_job)
data.nhom_cong_viec.explode().value_counts()

nhom_cong_viec
Software/Web/Mobile Development    6080
Management                         2039
Infrastructure & DevOps            1676
QA & Testing                       1309
Data & AI                          1206
Other                               666
Cybersecurity                       644
IT Solution & Consulting            607
Business Analysis                   573
Support                             368
Design & UI/UX                      230
Name: count, dtype: int64

In [17]:
data.head()

,ten_cong_viec,ten_cong_ty,muc_luong,dia_chi,ngay_dang,nganh_nghe,quy_mo_cong_ty,quoc_tich_cong_ty,nam_kinh_nghiem,cap_bac,...,loai_hop_dong,cong_nghe_su_dung,quy_trinh_phong_van,mo_ta_cong_viec,thong_tin_cong_ty,url,thoi_gian_hien_tai,url_cong_ty,so_luong_nhan_vien,nhom_cong_viec
0,Senior Full-stack Developer,CÔNG TY CỔ PHẦN IZOTA,"[0, 0]","[20/33a Đồng Xoài, Phường 13, Quận Tân Bình, T...",Đăng 1 ngày trước,[],Khong co thong tin,[],3.0,[Senior],...,[Fulltime],"[JavaScript, Python, .NET]",[],iZOTA focuses on accelerating digital transfor...,Về chúng tôi\nChế độ đãi ngộ,https://topdev.vn/viec-lam/senior-full-stack-d...,2024-11-03 21:38:30,https://topdev.vn/vi/nha-tuyen-dung/cong-ty-co...,"[0, 2000000]",[Software/Web/Mobile Development]
1,Software Development Specialist (DEV) – Positi...,BIDV - Trung tâm Phát triển ngân hàng số,"[0, 0]","[Tháp A Vincom, 191 Bà Triệu, Phường Lê Đại Hà...",Đăng 1 ngày trước,[Ngân Hàng],Lớn,[Vietnam],1.0,"[Junior, Middle, Senior]",...,[Fulltime],"[Java, ReactJS, Restful Api, Flutter, Spring B...","[Vòng 1: Sơ tuyển hồ sơ, Vòng 2: Phỏng vấn (Ng...",Trách nhiệm công việc\nDev Mobile\nXây dựng fr...,Về chúng tôi\nNgân hàng TMCP Đầu tư và Phát tr...,https://topdev.vn/viec-lam/chuyen-vien-phat-tr...,2024-11-03 21:38:30,https://topdev.vn/nha-tuyen-dung/bidv-trung-ta...,"[1000, 2000000]",[Software/Web/Mobile Development]
2,"[DI6] Solution Architect (Aws, Java)- MSB - 1Y564",Ngân hàng TMCP Hàng Hải Việt Nam (MSB),"[2500.0, 3500.0]","[TNR Tower, Số 54A Nguyễn Chí Thanh, Phường Lá...",Đăng 1 ngày trước,"[Ngân Hàng, Tài Chính, Công nghệ thông tin]",Lớn,[Vietnam],3.0,"[Junior, Senior]",...,[Fulltime],"[Java, Python, AWS, Business Intelligence, Sol...",[],Trách nhiệm công việc\n1. Quản trị Kiến trúc C...,"Về chúng tôi\nNgay từ khi thành lập, MSB đã gh...",https://topdev.vn/viec-lam/di6-solution-archit...,2024-11-03 21:38:30,https://topdev.vn/nha-tuyen-dung/ngan-hang-tmc...,"[1000, 2000000]","[IT Solution & Consulting, Infrastructure & De..."
3,"Manager (JLPT N2, Sign-on Bonus)",NEC Vietnam,"[0, 0]","[Tòa nhà Gelex, 52 Lê Đại Hành, Phường Lê Đại ...",Đăng 1 ngày trước,[Phần Mềm],Vừa,[Japan],5.0,[Trưởng phòng],...,[Fulltime],"[Manager, Project Manager, Japanese - N2, Japa...","[Vòng 1: Deputy Division Manager + HR, Vòng 2:...",ONE OF THE TOP ICT JAPANESE COMPANIES IN VIETN...,Về chúng tôi\nNEC established its liaison offi...,https://topdev.vn/viec-lam/manager-jlpt-n2-sig...,2024-11-03 21:38:30,https://topdev.vn/nha-tuyen-dung/nec-vietnam-7...,"[100, 499]",[Management]
4,"Backend Developer (Java, Python, NodeJS)",Ngân hàng TMCP An Bình (ABBANK),"[1500.0, 2200.0]","[36 Hoàng Cầu, Phường Ô Chợ Dừa, Quận Đống Đa,...",Đăng 1 ngày trước,[Ngân Hàng],Lớn,[Vietnam],5.0,"[Middle, Senior]",...,[Fulltime],"[Java, Python, NodeJS, MongoDB, PostgreSql]",[],"Trách nhiệm công việc\nLập trình, phát triển c...",Về chúng tôi\nNgân hàng TMCP An Bình (ABBANK) ...,https://topdev.vn/viec-lam/backend-developer-j...,2024-11-03 21:38:30,https://topdev.vn/nha-tuyen-dung/ngan-hang-tmc...,"[1000, 2000000]",[Software/Web/Mobile Development]

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12231 entries, 0 to 748
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_cong_viec        12231 non-null  object
 1   ten_cong_ty          12231 non-null  object
 2   muc_luong            12231 non-null  object
 3   dia_chi              12231 non-null  object
 4   ngay_dang            12231 non-null  object
 5   nganh_nghe           12231 non-null  object
 6   quy_mo_cong_ty       12231 non-null  object
 7   quoc_tich_cong_ty    12231 non-null  object
 8   nam_kinh_nghiem      12231 non-null  float64
 9   cap_bac              12231 non-null  object
 10  loai_hinh            12231 non-null  object
 11  loai_hop_dong        12231 non-null  object
 12  cong_nghe_su_dung    12231 non-null  object
 13  quy_trinh_phong_van  12231 non-null  object
 14  mo_ta_cong_viec      12231 non-null  object
 15  thong_tin_cong_ty    12231 non-null  object
 16  url                  12231 non-null  object
 17  thoi_gian_hien_tai   12231 non-null  datetime64[ns]
 18  url_cong_ty          12231 non-null  object
 19  so_luong_nhan_vien   12231 non-null  object
 20  nhom_cong_viec       12231 non-null  object
dtypes: datetime64[ns](1), float64(1), object(19)
memory usage: 2.1+ MB

# Push to MongoDB Atlas (Cloud Database)

In [19]:
from IPython.display import display, Markdown
from pymongo.mongo_client import MongoClient
from bson.objectid import ObjectId

In [20]:
uri = "mongodb+srv://endgame:endgame@cluster0.rkdhc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri)

# Send a ping to confirm a successful connection
try:
    client.admin.command("ping")
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

db = client["udptdltm"]
collection = db["data"]

Pinged your deployment. You successfully connected to MongoDB!

> Check the len of the database before

In [21]:
object_ids = [doc["_id"] for doc in collection.find({}, {"_id": 1})]
len(object_ids)

0

> Push to cloud

In [22]:
tmp = []
for i in range(data.shape[0]):
    tmp.append(data.iloc[i].to_dict())

collection.insert_many(tmp)

InsertManyResult([ObjectId('69b96f3f4c00379a2048e9e7'), ObjectId('69b96f3f4c00379a2048e9e8'), ObjectId('69b96f3f4c00379a2048e9e9'), ObjectId('69b96f3f4c00379a2048e9ea'), ObjectId('69b96f3f4c00379a2048e9eb'), ObjectId('69b96f3f4c00379a2048e9ec'), ObjectId('69b96f3f4c00379a2048e9ed'), ObjectId('69b96f3f4c00379a2048e9ee'), ObjectId('69b96f3f4c00379a2048e9ef'), ObjectId('69b96f3f4c00379a2048e9f0'), ObjectId('69b96f3f4c00379a2048e9f1'), ObjectId('69b96f3f4c00379a2048e9f2'), ObjectId('69b96f3f4c00379a2048e9f3'), ObjectId('69b96f3f4c00379a2048e9f4'), ObjectId('69b96f3f4c00379a2048e9f5'), ObjectId('69b96f3f4c00379a2048e9f6'), ObjectId('69b96f3f4c00379a2048e9f7'), ObjectId('69b96f3f4c00379a2048e9f8'), ObjectId('69b96f3f4c00379a2048e9f9'), ObjectId('69b96f3f4c00379a2048e9fa'), ObjectId('69b96f3f4c00379a2048e9fb'), ObjectId('69b96f3f4c00379a2048e9fc'), ObjectId('69b96f3f4c00379a2048e9fd'), ObjectId('69b96f3f4c00379a2048e9fe'), ObjectId('69b96f3f4c00379a2048e9ff'), ObjectId('69b96f3f4c00379a2048ea00'), ObjectId('69b96f3f4c00379a2048ea01'), ObjectId('69b96f3f4c00379a2048ea02'), ObjectId('69b96f3f4c00379a2048ea03'), ObjectId('69b96f3f4c00379a2048ea04'), ObjectId('69b96f3f4c00379a2048ea05'), ObjectId('69b96f3f4c00379a2048ea06'), ObjectId('69b96f3f4c00379a2048ea07'), ObjectId('69b96f3f4c00379a2048ea08'), ObjectId('69b96f3f4c00379a2048ea09'), ObjectId('69b96f3f4c00379a2048ea0a'), ObjectId('69b96f3f4c00379a2048ea0b'), ObjectId('69b96f3f4c00379a2048ea0c'), ObjectId('69b96f3f4c00379a2048ea0d'), ObjectId('69b96f3f4c00379a2048ea0e'), ObjectId('69b96f3f4c00379a2048ea0f'), ObjectId('69b96f3f4c00379a2048ea10'), ObjectId('69b96f3f4c00379a2048ea11'), ObjectId('69b96f3f4c00379a2048ea12'), ObjectId('69b96f3f4c00379a2048ea13'), ObjectId('69b96f3f4c00379a2048ea14'), ObjectId('69b96f3f4c00379a2048ea15'), ObjectId('69b96f3f4c00379a2048ea16'), ObjectId('69b96f3f4c00379a2048ea17'), ObjectId('69b96f3f4c00379a2048ea18'), ObjectId('69b96f3f4c00379a2048ea19'), ObjectId('69b96f3f4c00379a2048ea1a'), ObjectId('69b96f3f4c00379a2048ea1b'), ObjectId('69b96f3f4c00379a2048ea1c'), ObjectId('69b96f3f4c00379a2048ea1d'), ObjectId('69b96f3f4c00379a2048ea1e'), ObjectId('69b96f3f4c00379a2048ea1f'), ObjectId('69b96f3f4c00379a2048ea20'), ObjectId('69b96f3f4c00379a2048ea21'), ObjectId('69b96f3f4c00379a2048ea22'), ObjectId('69b96f3f4c00379a2048ea23'), ObjectId('69b96f3f4c00379a2048ea24'), ObjectId('69b96f3f4c00379a2048ea25'), ObjectId('69b96f3f4c00379a2048ea26'), ObjectId('69b96f3f4c00379a2048ea27'), ObjectId('69b96f3f4c00379a2048ea28'), ObjectId('69b96f3f4c00379a2048ea29'), ObjectId('69b96f3f4c00379a2048ea2a'), ObjectId('69b96f3f4c00379a2048ea2b'), ObjectId('69b96f3f4c00379a2048ea2c'), ObjectId('69b96f3f4c00379a2048ea2d'), ObjectId('69b96f3f4c00379a2048ea2e'), ObjectId('69b96f3f4c00379a2048ea2f'), ObjectId('69b96f3f4c00379a2048ea30'), ObjectId('69b96f3f4c00379a2048ea31'), ObjectId('69b96f3f4c00379a2048ea32'), ObjectId('69b96f3f4c00379a2048ea33'), ObjectId('69b96f3f4c00379a2048ea34'), ObjectId('69b96f3f4c00379a2048ea35'), ObjectId('69b96f3f4c00379a2048ea36'), ObjectId('69b96f3f4c00379a2048ea37'), ObjectId('69b96f3f4c00379a2048ea38'), ObjectId('69b96f3f4c00379a2048ea39'), ObjectId('69b96f3f4c00379a2048ea3a'), ObjectId('69b96f3f4c00379a2048ea3b'), ObjectId('69b96f3f4c00379a2048ea3c'), ObjectId('69b96f3f4c00379a2048ea3d'), ObjectId('69b96f3f4c00379a2048ea3e'), ObjectId('69b96f3f4c00379a2048ea3f'), ObjectId('69b96f3f4c00379a2048ea40'), ObjectId('69b96f3f4c00379a2048ea41'), ObjectId('69b96f3f4c00379a2048ea42'), ObjectId('69b96f3f4c00379a2048ea43'), ObjectId('69b96f3f4c00379a2048ea44'), ObjectId('69b96f3f4c00379a2048ea45'), ObjectId('69b96f3f4c00379a2048ea46'), ObjectId('69b96f3f4c00379a2048ea47'), ObjectId('69b96f3f4c00379a2048ea48'), ObjectId('69b96f3f4c00379a2048ea49'), ObjectId('69b96f3f4c00379a2048ea4a'), ObjectId('69b96f3f4c00379a2048ea4b'), ObjectId('69b96f3f4c00379a2048ea4c'), ObjectId('69b96f3f4c00379a2048ea4d'), ObjectId('69b96f3f4c00379a2048ea4e'), ObjectId('69b96f3f4c00379a2048ea4f'), ObjectId('69b96f3f4c00379a2048ea50'), ObjectId('69b96f3f4c00379a2048ea51'), ObjectId('69b96f3f4c00379a2048ea52'), ObjectId('69b96f3f4c00379a2048ea53'), ObjectId('69b96f3f4c00379a2048ea54'), ObjectId('69b96f3f4c00379a2048ea55'), ObjectId('69b96f3f4c00379a2048ea56'), ObjectId('69b96f3f4c00379a2048ea57'), ObjectId('69b96f3f4c00379a2048ea58'), ObjectId('69b96f3f4c00379a2048ea59'), ObjectId('69b96f3f4c00379a2048ea5a'), ObjectId('69b96f3f4c00379a2048ea5b'), ObjectId('69b96f3f4c00379a2048ea5c'), ObjectId('69b96f3f4c00379a2048ea5d'), ObjectId('69b96f3f4c00379a2048ea5e'), ObjectId('69b96f3f4c00379a2048ea5f'), ObjectId('69b96f3f4c00379a2048ea60'), ObjectId('69b96f3f4c00379a2048ea61'), ObjectId('69b96f3f4c00379a2048ea62'), ObjectId('69b96f3f4c00379a2048ea63'), ObjectId('69b96f3f4c00379a2048ea64'), ObjectId('69b96f3f4c00379a2048ea65'), ObjectId('69b96f3f4c00379a2048ea66'), ObjectId('69b96f3f4c00379a2048ea67'), ObjectId('69b96f3f4c00379a2048ea68'), ObjectId('69b96f3f4c00379a2048ea69'), ObjectId('69b96f3f4c00379a2048ea6a'), ObjectId('69b96f3f4c00379a2048ea6b'), ObjectId('69b96f3f4c00379a2048ea6c'), ObjectId('69b96f3f4c00379a2048ea6d'), ObjectId('69b96f3f4c00379a2048ea6e'), ObjectId('69b96f3f4c00379a2048ea6f'), ObjectId('69b96f3f4c00379a2048ea70'), ObjectId('69b96f3f4c00379a2048ea71'), ObjectId('69b96f3f4c00379a2048ea72'), ObjectId('69b96f3f4c00379a2048ea73'), ObjectId('69b96f3f4c00379a2048ea74'), ObjectId('69b96f3f4c00379a2048ea75'), ObjectId('69b96f3f4c00379a2048ea76'), ObjectId('69b96f3f4c00379a2048ea77'), ObjectId('69b96f3f4c00379a2048ea78'), ObjectId('69b96f3f4c00379a2048ea79'), ObjectId('69b96f3f4c00379a2048ea7a'), ObjectId('69b96f3f4c00379a2048ea7b'), ObjectId('69b96f3f4c00379a2048ea7c'), ObjectId('69b96f3f4c00379a2048ea7d'), ObjectId('69b96f3f4c00379a2048ea7e'), ObjectId('69b96f3f4c00379a2048ea7f'), ObjectId('69b96f3f4c00379a2048ea80'), ObjectId('69b96f3f4c00379a2048ea81'), ObjectId('69b96f3f4c00379a2048ea82'), ObjectId('69b96f3f4c00379a2048ea83'), ObjectId('69b96f3f4c00379a2048ea84'), ObjectId('69b96f3f4c00379a2048ea85'), ObjectId('69b96f3f4c00379a2048ea86'), ObjectId('69b96f3f4c00379a2048ea87'), ObjectId('69b96f3f4c00379a2048ea88'), ObjectId('69b96f3f4c00379a2048ea89'), ObjectId('69b96f3f4c00379a2048ea8a'), ObjectId('69b96f3f4c00379a2048ea8b'), ObjectId('69b96f3f4c00379a2048ea8c'), ObjectId('69b96f3f4c00379a2048ea8d'), ObjectId('69b96f3f4c00379a2048ea8e'), ObjectId('69b96f3f4c00379a2048ea8f'), ObjectId('69b96f3f4c00379a2048ea90'), ObjectId('69b96f3f4c00379a2048ea91'), ObjectId('69b96f3f4c00379a2048ea92'), ObjectId('69b96f3f4c00379a2048ea93'), ObjectId('69b96f3f4c00379a2048ea94'), ObjectId('69b96f3f4c00379a2048ea95'), ObjectId('69b96f3f4c00379a2048ea96'), ObjectId('69b96f3f4c00379a2048ea97'), ObjectId('69b96f3f4c00379a2048ea98'), ObjectId('69b96f3f4c00379a2048ea99'), ObjectId('69b96f3f4c00379a2048ea9a'), ObjectId('69b96f3f4c00379a2048ea9b'), ObjectId('69b96f3f4c00379a2048ea9c'), ObjectId('69b96f3f4c00379a2048ea9d'), ObjectId('69b96f3f4c00379a2048ea9e'), ObjectId('69b96f3f4c00379a2048ea9f'), ObjectId('69b96f3f4c00379a2048eaa0'), ObjectId('69b96f3f4c00379a2048eaa1'), ObjectId('69b96f3f4c00379a2048eaa2'), ObjectId('69b96f3f4c00379a2048eaa3'), ObjectId('69b96f3f4c00379a2048eaa4'), ObjectId('69b96f3f4c00379a2048eaa5'), ObjectId('69b96f3f4c00379a2048eaa6'), ObjectId('69b96f3f4c00379a2048eaa7'), ObjectId('69b96f3f4c00379a2048eaa8'), ObjectId('69b96f3f4c00379a2048eaa9'), ObjectId('69b96f3f4c00379a2048eaaa'), ObjectId('69b96f3f4c00379a2048eaab'), ObjectId('69b96f3f4c00379a2048eaac'), ObjectId('69b96f3f4c00379a2048eaad'), ObjectId('69b96f3f4c00379a2048eaae'), ObjectId('69b96f3f4c00379a2048eaaf'), ObjectId('69b96f3f4c00379a2048eab0'), ObjectId('69b96f3f4c00379a2048eab1'), ObjectId('69b96f3f4c00379a2048eab2'), ObjectId('69b96f3f4c00379a2048eab3'), ObjectId('69b96f3f4c00379a2048eab4'), ObjectId('69b96f3f4c00379a2048eab5'), ObjectId('69b96f3f4c00379a2048eab6'), ObjectId('69b96f3f4c00379a2048eab7'), ObjectId('69b96f3f4c00379a2048eab8'), ObjectId('69b96f3f4c00379a2048eab9'), ObjectId('69b96f3f4c00379a2048eaba'), ObjectId('69b96f3f4c00379a2048eabb'), ObjectId('69b96f3f4c00379a2048eabc'), ObjectId('69b96f3f4c00379a2048eabd'), ObjectId('69b96f3f4c00379a2048eabe'), ObjectId('69b96f3f4c00379a2048eabf'), ObjectId('69b96f3f4c00379a2048eac0'), ObjectId('69b96f3f4c00379a2048eac1'), ObjectId('69b96f3f4c00379a2048eac2'), ObjectId('69b96f3f4c00379a2048eac3'), ObjectId('69b96f3f4c00379a2048eac4'), ObjectId('69b96f3f4c00379a2048eac5'), ObjectId('69b96f3f4c00379a2048eac6'), ObjectId('69b96f3f4c00379a2048eac7'), ObjectId('69b96f3f4c00379a2048eac8'), ObjectId('69b96f3f4c00379a2048eac9'), ObjectId('69b96f3f4c00379a2048eaca'), ObjectId('69b96f3f4c00379a2048eacb'), ObjectId('69b96f3f4c00379a2048eacc'), ObjectId('69b96f3f4c00379a2048eacd'), ObjectId('69b96f3f4c00379a2048eace'), ObjectId('69b96f3f4c00379a2048eacf'), ObjectId('69b96f3f4c00379a2048ead0'), ObjectId('69b96f3f4c00379a2048ead1'), ObjectId('69b96f3f4c00379a2048ead2'), ObjectId('69b96f3f4c00379a2048ead3'), ObjectId('69b96f3f4c00379a2048ead4'), ObjectId('69b96f3f4c00379a2048ead5'), ObjectId('69b96f3f4c00379a2048ead6'), ObjectId('69b96f3f4c00379a2048ead7'), ObjectId('69b96f3f4c00379a2048ead8'), ObjectId('69b96f3f4c00379a2048ead9'), ObjectId('69b96f3f4c00379a2048eada'), ObjectId('69b96f3f4c00379a2048eadb'), ObjectId('69b96f3f4c00379a2048eadc'), ObjectId('69b96f3f4c00379a2048eadd'), ObjectId('69b96f3f4c00379a2048eade'), ObjectId('69b96f3f4c00379a2048eadf'), ObjectId('69b96f3f4c00379a2048eae0'), ObjectId('69b96f3f4c00379a2048eae1'), ObjectId('69b96f3f4c00379a2048eae2'), ObjectId('69b96f3f4c00379a2048eae3'), ObjectId('69b96f3f4c00379a2048eae4'), ObjectId('69b96f3f4c00379a2048eae5'), ObjectId('69b96f3f4c00379a2048eae6'), ObjectId('69b96f3f4c00379a2048eae7'), ObjectId('69b96f3f4c00379a2048eae8'), ObjectId('69b96f3f4c00379a2048eae9'), ObjectId('69b96f3f4c00379a2048eaea'), ObjectId('69b96f3f4c00379a2048eaeb'), ObjectId('69b96f3f4c00379a2048eaec'), ObjectId('69b96f3f4c00379a2048eaed'), ObjectId('69b96f3f4c00379a2048eaee'), ObjectId('69b96f3f4c00379a2048eaef'), ObjectId('69b96f3f4c00379a2048eaf0'), ObjectId('69b96f3f4c00379a2048eaf1'), ObjectId('69b96f3f4c00379a2048eaf2'), ObjectId('69b96f3f4c00379a2048eaf3'), ObjectId('69b96f3f4c00379a2048eaf4'), ObjectId('69b96f3f4c00379a2048eaf5'), ObjectId('69b96f3f4c00379a2048eaf6'), ObjectId('69b96f3f4c00379a2048eaf7'), ObjectId('69b96f3f4c00379a2048eaf8'), ObjectId('69b96f3f4c00379a2048eaf9'), ObjectId('69b96f3f4c00379a2048eafa'), ObjectId('69b96f3f4c00379a2048eafb'), ObjectId('69b96f3f4c00379a2048eafc'), ObjectId('69b96f3f4c00379a2048eafd'), ObjectId('69b96f3f4c00379a2048eafe'), ObjectId('69b96f3f4c00379a2048eaff'), ObjectId('69b96f3f4c00379a2048eb00'), ObjectId('69b96f3f4c00379a2048eb01'), ObjectId('69b96f3f4c00379a2048eb02'), ObjectId('69b96f3f4c00379a2048eb03'), ObjectId('69b96f3f4c00379a2048eb04'), ObjectId('69b96f3f4c00379a2048eb05'), ObjectId('69b96f3f4c00379a2048eb06'), ObjectId('69b96f3f4c00379a2048eb07'), ObjectId('69b96f3f4c00379a2048eb08'), ObjectId('69b96f3f4c00379a2048eb09'), ObjectId('69b96f3f4c00379a2048eb0a'), ObjectId('69b96f3f4c00379a2048eb0b'), ObjectId('69b96f3f4c00379a2048eb0c'), ObjectId('69b96f3f4c00379a2048eb0d'), ObjectId('69b96f3f4c00379a2048eb0e'), ObjectId('69b96f3f4c00379a2048eb0f'), ObjectId('69b96f3f4c00379a2048eb10'), ObjectId('69b96f3f4c00379a2048eb11'), ObjectId('69b96f3f4c00379a2048eb12'), ObjectId('69b96f3f4c00379a2048eb13'), ObjectId('69b96f3f4c00379a2048eb14'), ObjectId('69b96f3f4c00379a2048eb15'), ObjectId('69b96f3f4c00379a2048eb16'), ObjectId('69b96f3f4c00379a2048eb17'), ObjectId('69b96f3f4c00379a2048eb18'), ObjectId('69b96f3f4c00379a2048eb19'), ObjectId('69b96f3f4c00379a2048eb1a'), ObjectId('69b96f3f4c00379a2048eb1b'), ObjectId('69b96f3f4c00379a2048eb1c'), ObjectId('69b96f3f4c00379a2048eb1d'), ObjectId('69b96f3f4c00379a2048eb1e'), ObjectId('69b96f3f4c00379a2048eb1f'), ObjectId('69b96f3f4c00379a2048eb20'), ObjectId('69b96f3f4c00379a2048eb21'), ObjectId('69b96f3f4c00379a2048eb22'), ObjectId('69b96f3f4c00379a2048eb23'), ObjectId('69b96f3f4c00379a2048eb24'), ObjectId('69b96f3f4c00379a2048eb25'), ObjectId('69b96f3f4c00379a2048eb26'), ObjectId('69b96f3f4c00379a2048eb27'), ObjectId('69b96f3f4c00379a2048eb28'), ObjectId('69b96f3f4c00379a2048eb29'), ObjectId('69b96f3f4c00379a2048eb2a'), ObjectId('69b96f3f4c00379a2048eb2b'), ObjectId('69b96f3f4c00379a2048eb2c'), ObjectId('69b96f3f4c00379a2048eb2d'), ObjectId('69b96f3f4c00379a2048eb2e'), ObjectId('69b96f3f4c00379a2048eb2f'), ObjectId('69b96f3f4c00379a2048eb30'), ObjectId('69b96f3f4c00379a2048eb31'), ObjectId('69b96f3f4c00379a2048eb32'), ObjectId('69b96f3f4c00379a2048eb33'), ObjectId('69b96f3f4c00379a2048eb34'), ObjectId('69b96f3f4c00379a2048eb35'), ObjectId('69b96f3f4c00379a2048eb36'), ObjectId('69b96f3f4c00379a2048eb37'), ObjectId('69b96f3f4c00379a2048eb38'), ObjectId('69b96f3f4c00379a2048eb39'), ObjectId('69b96f3f4c00379a2048eb3a'), ObjectId('69b96f3f4c00379a2048eb3b'), ObjectId('69b96f3f4c00379a2048eb3c'), ObjectId('69b96f3f4c00379a2048eb3d'), ObjectId('69b96f3f4c00379a2048eb3e'), ObjectId('69b96f3f4c00379a2048eb3f'), ObjectId('69b96f3f4c00379a2048eb40'), ObjectId('69b96f3f4c00379a2048eb41'), ObjectId('69b96f3f4c00379a2048eb42'), ObjectId('69b96f3f4c00379a2048eb43'), ObjectId('69b96f3f4c00379a2048eb44'), ObjectId('69b96f3f4c00379a2048eb45'), ObjectId('69b96f3f4c00379a2048eb46'), ObjectId('69b96f3f4c00379a2048eb47'), ObjectId('69b96f3f4c00379a2048eb48'), ObjectId('69b96f3f4c00379a2048eb49'), ObjectId('69b96f3f4c00379a2048eb4a'), ObjectId('69b96f3f4c00379a2048eb4b'), ObjectId('69b96f3f4c00379a2048eb4c'), ObjectId('69b96f3f4c00379a2048eb4d'), ObjectId('69b96f3f4c00379a2048eb4e'), ObjectId('69b96f3f4c00379a2048eb4f'), ObjectId('69b96f3f4c00379a2048eb50'), ObjectId('69b96f3f4c00379a2048eb51'), ObjectId('69b96f3f4c00379a2048eb52'), ObjectId('69b96f3f4c00379a2048eb53'), ObjectId('69b96f3f4c00379a2048eb54'), ObjectId('69b96f3f4c00379a2048eb55'), ObjectId('69b96f3f4c00379a2048eb56'), ObjectId('69b96f3f4c00379a2048eb57'), ObjectId('69b96f3f4c00379a2048eb58'), ObjectId('69b96f3f4c00379a2048eb59'), ObjectId('69b96f3f4c00379a2048eb5a'), ObjectId('69b96f3f4c00379a2048eb5b'), ObjectId('69b96f3f4c00379a2048eb5c'), ObjectId('69b96f3f4c00379a2048eb5d'), ObjectId('69b96f3f4c00379a2048eb5e'), ObjectId('69b96f3f4c00379a2048eb5f'), ObjectId('69b96f3f4c00379a2048eb60'), ObjectId('69b96f3f4c00379a2048eb61'), ObjectId('69b96f3f4c00379a2048eb62'), ObjectId('69b96f3f4c00379a2048eb63'), ObjectId('69b96f3f4c00379a2048eb64'), ObjectId('69b96f3f4c00379a2048eb65'), ObjectId('69b96f3f4c00379a2048eb66'), ObjectId('69b96f3f4c00379a2048eb67'), ObjectId('69b96f3f4c00379a2048eb68'), ObjectId('69b96f3f4c00379a2048eb69'), ObjectId('69b96f3f4c00379a2048eb6a'), ObjectId('69b96f3f4c00379a2048eb6b'), ObjectId('69b96f3f4c00379a2048eb6c'), ObjectId('69b96f3f4c00379a2048eb6d'), ObjectId('69b96f3f4c00379a2048eb6e'), ObjectId('69b96f3f4c00379a2048eb6f'), ObjectId('69b96f3f4c00379a2048eb70'), ObjectId('69b96f3f4c00379a2048eb71'), ObjectId('69b96f3f4c00379a2048eb72'), ObjectId('69b96f3f4c00379a2048eb73'), ObjectId('69b96f3f4c00379a2048eb74'), ObjectId('69b96f3f4c00379a2048eb75'), ObjectId('69b96f3f4c00379a2048eb76'), ObjectId('69b96f3f4c00379a2048eb77'), ObjectId('69b96f3f4c00379a2048eb78'), ObjectId('69b96f3f4c00379a2048eb79'), ObjectId('69b96f3f4c00379a2048eb7a'), ObjectId('69b96f3f4c00379a2048eb7b'), ObjectId('69b96f3f4c00379a2048eb7c'), ObjectId('69b96f3f4c00379a2048eb7d'), ObjectId('69b96f3f4c00379a2048eb7e'), ObjectId('69b96f3f4c00379a2048eb7f'), ObjectId('69b96f3f4c00379a2048eb80'), ObjectId('69b96f3f4c00379a2048eb81'), ObjectId('69b96f3f4c00379a2048eb82'), ObjectId('69b96f3f4c00379a2048eb83'), ObjectId('69b96f3f4c00379a2048eb84'), ObjectId('69b96f3f4c00379a2048eb85'), ObjectId('69b96f3f4c00379a2048eb86'), ObjectId('69b96f3f4c00379a2048eb87'), ObjectId('69b96f3f4c00379a2048eb88'), ObjectId('69b96f3f4c00379a2048eb89'), ObjectId('69b96f3f4c00379a2048eb8a'), ObjectId('69b96f3f4c00379a2048eb8b'), ObjectId('69b96f3f4c00379a2048eb8c'), ObjectId('69b96f3f4c00379a2048eb8d'), ObjectId('69b96f3f4c00379a2048eb8e'), ObjectId('69b96f3f4c00379a2048eb8f'), ObjectId('69b96f3f4c00379a2048eb90'), ObjectId('69b96f3f4c00379a2048eb91'), ObjectId('69b96f3f4c00379a2048eb92'), ObjectId('69b96f3f4c00379a2048eb93'), ObjectId('69b96f3f4c00379a2048eb94'), ObjectId('69b96f3f4c00379a2048eb95'), ObjectId('69b96f3f4c00379a2048eb96'), ObjectId('69b96f3f4c00379a2048eb97'), ObjectId('69b96f3f4c00379a2048eb98'), ObjectId('69b96f3f4c00379a2048eb99'), ObjectId('69b96f3f4c00379a2048eb9a'), ObjectId('69b96f3f4c00379a2048eb9b'), ObjectId('69b96f3f4c00379a2048eb9c'), ObjectId('69b96f3f4c00379a2048eb9d'), ObjectId('69b96f3f4c00379a2048eb9e'), ObjectId('69b96f3f4c00379a2048eb9f'), ObjectId('69b96f3f4c00379a2048eba0'), ObjectId('69b96f3f4c00379a2048eba1'), ObjectId('69b96f3f4c00379a2048eba2'), ObjectId('69b96f3f4c00379a2048eba3'), ObjectId('69b96f3f4c00379a2048eba4'), ObjectId('69b96f3f4c00379a2048eba5'), ObjectId('69b96f3f4c00379a2048eba6'), ObjectId('69b96f3f4c00379a2048eba7'), ObjectId('69b96f3f4c00379a2048eba8'), ObjectId('69b96f3f4c00379a2048eba9'), ObjectId('69b96f3f4c00379a2048ebaa'), ObjectId('69b96f3f4c00379a2048ebab'), ObjectId('69b96f3f4c00379a2048ebac'), ObjectId('69b96f3f4c00379a2048ebad'), ObjectId('69b96f3f4c00379a2048ebae'), ObjectId('69b96f3f4c00379a2048ebaf'), ObjectId('69b96f3f4c00379a2048ebb0'), ObjectId('69b96f3f4c00379a2048ebb1'), ObjectId('69b96f3f4c00379a2048ebb2'), ObjectId('69b96f3f4c00379a2048ebb3'), ObjectId('69b96f3f4c00379a2048ebb4'), ObjectId('69b96f3f4c00379a2048ebb5'), ObjectId('69b96f3f4c00379a2048ebb6'), ObjectId('69b96f3f4c00379a2048ebb7'), ObjectId('69b96f3f4c00379a2048ebb8'), ObjectId('69b96f3f4c00379a2048ebb9'), ObjectId('69b96f3f4c00379a2048ebba'), ObjectId('69b96f3f4c00379a2048ebbb'), ObjectId('69b96f3f4c00379a2048ebbc'), ObjectId('69b96f3f4c00379a2048ebbd'), ObjectId('69b96f3f4c00379a2048ebbe'), ObjectId('69b96f3f4c00379a2048ebbf'), ObjectId('69b96f3f4c00379a2048ebc0'), ObjectId('69b96f3f4c00379a2048ebc1'), ObjectId('69b96f3f4c00379a2048ebc2'), ObjectId('69b96f3f4c00379a2048ebc3'), ObjectId('69b96f3f4c00379a2048ebc4'), ObjectId('69b96f3f4c00379a2048ebc5'), ObjectId('69b96f3f4c00379a2048ebc6'), ObjectId('69b96f3f4c00379a2048ebc7'), ObjectId('69b96f3f4c00379a2048ebc8'), ObjectId('69b96f3f4c00379a2048ebc9'), ObjectId('69b96f3f4c00379a2048ebca'), ObjectId('69b96f3f4c00379a2048ebcb'), ObjectId('69b96f3f4c00379a2048ebcc'), ObjectId('69b96f3f4c00379a2048ebcd'), ObjectId('69b96f3f4c00379a2048ebce'), ObjectId('69b96f3f4c00379a2048ebcf'), ObjectId('69b96f3f4c00379a2048ebd0'), ObjectId('69b96f3f4c00379a2048ebd1'), ObjectId('69b96f3f4c00379a2048ebd2'), ObjectId('69b96f3f4c00379a2048ebd3'), ObjectId('69b96f3f4c00379a2048ebd4'), ObjectId('69b96f3f4c00379a2048ebd5'), ObjectId('69b96f3f4c00379a2048ebd6'), ObjectId('69b96f3f4c00379a2048ebd7'), ObjectId('69b96f3f4c00379a2048ebd8'), ObjectId('69b96f3f4c00379a2048ebd9'), ObjectId('69b96f3f4c00379a2048ebda'), ObjectId('69b96f3f4c00379a2048ebdb'), ObjectId('69b96f3f4c00379a2048ebdc'), ObjectId('69b96f3f4c00379a2048ebdd'), ObjectId('69b96f3f4c00379a2048ebde'), ObjectId('69b96f3f4c00379a2048ebdf'), ObjectId('69b96f3f4c00379a2048ebe0'), ObjectId('69b96f3f4c00379a2048ebe1'), ObjectId('69b96f3f4c00379a2048ebe2'), ObjectId('69b96f3f4c00379a2048ebe3'), ObjectId('69b96f3f4c00379a2048ebe4'), ObjectId('69b96f3f4c00379a2048ebe5'), ObjectId('69b96f3f4c00379a2048ebe6'), ObjectId('69b96f3f4c00379a2048ebe7'), ObjectId('69b96f3f4c00379a2048ebe8'), ObjectId('69b96f3f4c00379a2048ebe9'), ObjectId('69b96f3f4c00379a2048ebea'), ObjectId('69b96f3f4c00379a2048ebeb'), ObjectId('69b96f3f4c00379a2048ebec'), ObjectId('69b96f3f4c00379a2048ebed'), ObjectId('69b96f3f4c00379a2048ebee'), ObjectId('69b96f3f4c00379a2048ebef'), ObjectId('69b96f3f4c00379a2048ebf0'), ObjectId('69b96f3f4c00379a2048ebf1'), ObjectId('69b96f3f4c00379a2048ebf2'), ObjectId('69b96f3f4c00379a2048ebf3'), ObjectId('69b96f3f4c00379a2048eb

> Check the len of the database after

In [23]:
object_ids = [doc["_id"] for doc in collection.find({}, {"_id": 1})]
len(object_ids)

12231

In [24]:
collection.distinct("thoi_gian_hien_tai")

[datetime.datetime(2024, 10, 29, 23, 49, 40, 410000),
 datetime.datetime(2024, 10, 30, 21, 12, 27, 898000),
 datetime.datetime(2024, 10, 31, 22, 31, 43, 598000),
 datetime.datetime(2024, 11, 1, 18, 57, 33, 986000),
 datetime.datetime(2024, 11, 2, 21, 31, 49, 226000),
 datetime.datetime(2024, 11, 3, 21, 38, 30),
 datetime.datetime(2024, 11, 4, 22, 16, 5, 607000),
 datetime.datetime(2024, 11, 5, 21, 36, 12, 594000),
 datetime.datetime(2024, 11, 6, 22, 21, 3, 196000),
 datetime.datetime(2024, 11, 7, 21, 16, 27, 26000),
 datetime.datetime(2024, 11, 8, 21, 29, 37, 990000),
 datetime.datetime(2024, 11, 9, 22, 2, 25, 48000),
 datetime.datetime(2024, 11, 10, 20, 31, 45, 149000),
 datetime.datetime(2024, 11, 11, 14, 20, 13, 537000),
 datetime.datetime(2024, 11, 12, 21, 37, 52, 656000),
 datetime.datetime(2024, 11, 13, 13, 39, 32, 143000),
 datetime.datetime(2024, 11, 14, 14, 45, 15, 444000),
 datetime.datetime(2024, 11, 15, 21, 20, 17, 292000),
 datetime.datetime(2024, 11, 16, 20, 54, 43, 495000),
 datetime.datetime(2024, 11, 17, 21, 55, 19, 72000),
 datetime.datetime(2024, 11, 18, 22, 27, 2, 468000),
 datetime.datetime(2024, 11, 19, 21, 47, 19, 572000),
 datetime.datetime(2024, 11, 20, 21, 33, 28, 6000),
 datetime.datetime(2024, 11, 21, 21, 37, 42, 229000),
 datetime.datetime(2024, 11, 22, 22, 20, 46, 415000),
 datetime.datetime(2024, 11, 23, 21, 26, 46, 48000),
 datetime.datetime(2024, 11, 24, 23, 46, 54, 600000),
 datetime.datetime(2024, 11, 25, 22, 23, 41, 205000),
 datetime.datetime(2024, 11, 26, 22, 19, 4, 541000),
 datetime.datetime(2024, 11, 27, 21, 15, 26, 441000),
 datetime.datetime(2024, 11, 28, 20, 55, 17, 541000),
 datetime.datetime(2024, 11, 29, 21, 57, 1, 42000),
 datetime.datetime(2024, 11, 30, 23, 58, 53, 998000),
 datetime.datetime(2024, 12, 1, 20, 32, 28, 498000),
 datetime.datetime(2024, 12, 2, 22, 24, 5, 29000),
 datetime.datetime(2024, 12, 3, 21, 28, 28, 210000),
 datetime.datetime(2024, 12, 4, 20, 53, 14, 194000),
 datetime.datetime(2024, 12, 5, 20, 26, 25, 371000),
 datetime.datetime(2024, 12, 6, 14, 31, 57, 937000)]

In [25]:
df = data.drop_duplicates(subset="url", keep="first").reset_index(drop=True)
df.to_csv("../data/processed_data.csv", index=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_cong_viec        537 non-null    object
 1   ten_cong_ty          537 non-null    object
 2   muc_luong            537 non-null    object
 3   dia_chi              537 non-null    object
 4   ngay_dang            537 non-null    object
 5   nganh_nghe           537 non-null    object
 6   quy_mo_cong_ty       537 non-null    object
 7   quoc_tich_cong_ty    537 non-null    object
 8   nam_kinh_nghiem      537 non-null    float64
 9   cap_bac              537 non-null    object
 10  loai_hinh            537 non-null    object
 11  loai_hop_dong        537 non-null    object
 12  cong_nghe_su_dung    537 non-null    object
 13  quy_trinh_phong_van  537 non-null    object
 14  mo_ta_cong_viec      537 non-null    object
 15  thong_tin_cong_ty    537 non-null    object
 16  url                  537 non-null    object
 17  thoi_gian_hien_tai   537 non-null    datetime64[ns]
 18  url_cong_ty          537 non-null    object
 19  so_luong_nhan_vien   537 non-null    object
 20  nhom_cong_viec       537 non-null    object
dtypes: datetime64[ns](1), float64(1), object(19)
memory usage: 88.2+ KB