# Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import ast
import os

# from IPython.display import display, Markdown
# from pymongo.mongo_client import MongoClient
# from bson.objectid import ObjectId

# %pip install deep-translator
from deep_translator import GoogleTranslator

In [2]:
# Define the directory containing the CSV files
directory = "csv_backup"

# Initialize an empty list to store DataFrames
dataframes = []

# Loop through all files in the directory
for filename in os.listdir(directory):
    if filename.endswith(".csv"):  # Check if the file is a CSV
        file_path = os.path.join(directory, filename)
        # Read the CSV file into a DataFrame
        df = pd.read_csv(file_path)
        ### DROP DUPLICATES
        df = df.drop_duplicates()
        dataframes.append(df)

# Combine all DataFrames into a single DataFrame (optional)
data = pd.concat(dataframes)
data.head(3)

,ten_cong_viec,ten_cong_ty,muc_luong,dia_chi,ngay_dang,nganh_nghe,quy_mo_cong_ty,quoc_tich_cong_ty,nam_kinh_nghiem,cap_bac,loai_hinh,loai_hop_dong,cong_nghe_su_dung,quy_trinh_phong_van,mo_ta_cong_viec,thong_tin_cong_ty,url,thoi_gian_hien_tai,url_cong_ty
0,['Viettel Digital Service (VDS) - Senior Java ...,['Viettel Group'],[],"['Tòa Keangnam Landmark 72 tầng, đường Phạm Hù...",['Đăng 3 ngày trước'],"['Viễn Thông, Phần Mềm, Dịch vụ doanh nghiệp']",['Hơn 1000 Nhân viên'],['Vietnam'],['Từ 5 năm'],['Senior'],['In Office'],['Fulltime'],"['Java', 'SQL', 'Java Core']","['Vòng 1: Test IQ, chuyên môn và ngoại ngữ', '...",['Tổng Công ty Dịch vụ số Viettel - Viettel Di...,Về chúng tôi\nTập đoàn Công nghiệp – Viễn thôn...,https://topdev.vn/viec-lam/viettel-digital-ser...,2024-12-03 21:28:28.210355,https://topdev.vn/vi/nha-tuyen-dung/viettel-gr...
1,"['Project Leader/ Team Leader (BrSE, Japanese)']",['NEC Vietnam'],['Thương lượng'],"['Lầu 9, Etown 3, 364 Cộng Hòa, Phường 13, Quậ...",['Đăng 2 ngày trước'],['Software'],['100-499 Nhân viên'],['Japan'],['Từ 5 năm'],"['Trưởng phòng, Trưởng Nhóm, Senior']",['Hybrid'],['Fulltime'],"['Japanese - N3', 'Japanese', 'BrSE', 'BSE Lea...",['Vòng 1: Interview with Hiring Managers'],['ONE OF THE TOP ICT JAPANESE COMPANIES IN VIE...,Về chúng tôi\nNEC established its liaison offi...,https://topdev.vn/viec-lam/project-leader-team...,2024-12-03 21:28:28.210355,https://topdev.vn/nha-tuyen-dung/nec-vietnam-7...
2,"['Senior Java Developer (JLPT N2, Sign-on Bonu...",['NEC Vietnam'],['Thương lượng'],"['Lầu 9, Etown 3, 364 Cộng Hòa, Phường 13, Quậ...",['Đăng 5 ngày trước'],['Software'],['100-499 Nhân viên'],['Japan'],['Từ 4 năm'],"['Trưởng Nhóm, Senior']",['Hybrid'],['Fulltime'],"['Java', 'Japanese - N3', 'Japanese - N2', 'Ja...",[],['ONE OF THE TOP ICT JAPANESE COMPANIES IN VIE...,Về chúng tôi\nNEC established its liaison offi...,https://topdev.vn/viec-lam/senior-java-develop...,2024-12-03 21:28:28.210355,https://topdev.vn/nha-tuyen-dung/nec-vietnam-7...

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12231 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_cong_viec        12231 non-null  object
 1   ten_cong_ty          12231 non-null  object
 2   muc_luong            12231 non-null  object
 3   dia_chi              12231 non-null  object
 4   ngay_dang            12231 non-null  object
 5   nganh_nghe           12231 non-null  object
 6   quy_mo_cong_ty       12231 non-null  object
 7   quoc_tich_cong_ty    12231 non-null  object
 8   nam_kinh_nghiem      12231 non-null  object
 9   cap_bac              12231 non-null  object
 10  loai_hinh            12231 non-null  object
 11  loai_hop_dong        12231 non-null  object
 12  cong_nghe_su_dung    12231 non-null  object
 13  quy_trinh_phong_van  12231 non-null  object
 14  mo_ta_cong_viec      12231 non-null  object
 15  thong_tin_cong_ty    12219 non-null  object
 16  url                  12231 non-null  object
 17  thoi_gian_hien_tai   12231 non-null  object
 18  url_cong_ty          12231 non-null  object
dtypes: object(19)
memory usage: 1.9+ MB

# Preprocess

In [4]:
data["muc_luong"] = data["muc_luong"].replace("[]", "['Thương lượng']")
data["thoi_gian_hien_tai"] = data["thoi_gian_hien_tai"].apply(pd.to_datetime)
for col in data.columns:
    if col in ["thong_tin_cong_ty", "url", "url_cong_ty", "thoi_gian_hien_tai"]:
        continue
    data[col] = data[col].apply(ast.literal_eval)


def getOnlyElement(series):
    return series[0]


for col in data.columns:
    if col in ["thong_tin_cong_ty", "url", "url_cong_ty", "thoi_gian_hien_tai"]:
        continue
    if col in [
        "dia_chi",
        "loai_hinh",
        "loai_hop_dong",
        "cong_nghe_su_dung",
        "quy_trinh_phong_van",
    ]:
        continue
    data[col] = data[col].apply(getOnlyElement)

In [5]:
def split_(series):
    return series.split(", ")

def castUSA(series):
    return series.replace("USA", "United States")

data["cap_bac"] = data.cap_bac.apply(split_)
data["quoc_tich_cong_ty"] = data.quoc_tich_cong_ty.apply(castUSA).apply(split_)

In [6]:
def split_domain(series):
    lst = series.split(", ")
    if "Phần Mềm" in lst or "Software" in lst:
        lst = [x for x in lst if x!="Phần Mềm" and x!="Software"]   
        lst.append("Phần Mềm")     
    return lst
data["nganh_nghe"] = data.nganh_nghe.apply(split_domain)

In [7]:
def experience(series):
    num = re.findall(r"\d+", series)
    if len(num) == 0:
        return 0
    num = num[0]
    if "tháng" in series:
        return int(num) * 1.0 / 12
    if "năm" in series:
        return int(num)
    return pd.NA


data["nam_kinh_nghiem"] = data.nam_kinh_nghiem.apply(experience)

In [8]:
def size(series):
    if "." in series:
        series = series.replace(".", "")
    num = re.findall(r"\d+", series)
    if len(num) == 0:
        return None
    res = int(num[0])
    if res < 100:
        return "Nhỏ"
    if res < 1000:
        return "Vừa"
    return "Lớn"

data["so_luong_nhan_vien"] = data.quy_mo_cong_ty
data["quy_mo_cong_ty"] = data.quy_mo_cong_ty.apply(size)

In [9]:
def n_number(series):
    if "." in series:
        series = series.replace(".", "")
    num = re.findall(r"\d+", series)
    if len(num) == 0:
        return [0, 2000000]
    if len(num) == 1:
        return [int(num[0]), 2000000]
    return [int(num[0]), int(num[1])]

data["so_luong_nhan_vien"] = data.so_luong_nhan_vien.apply(n_number)

In [10]:
def extract_salary_range(salary):
    if salary == "Thương lượng":
        return [0, 0]
    numbers = re.findall(r"[\d.,]+", salary)
    if numbers:
        numbers = [float(num.replace(".", "").strip()) for num in numbers]
        if len(numbers) == 1:
            if numbers[0] > 1_000_000:
                numbers[0] = numbers[0] / 24_000
            return [0, round(numbers[0], 2)]
        for i in range(len(numbers)):
            if numbers[i] > 1_000_000:
                numbers[i] = numbers[i] / 24_000

        # Lấy giá trị nhỏ nhất và lớn nhất
        min_value = min(numbers)
        max_value = max(numbers)

        return [round(min_value, 2), round(max_value, 2)]
    return [0, 0]


data["muc_luong"] = data["muc_luong"].apply(extract_salary_range)

In [11]:
data.replace("", pd.NA, inplace=True)
data.replace(pd.NA, "Khong co thong tin", inplace=True)

## Translate the job title into English

In [12]:
# 2. Hàm dịch tự động sử dụng Deep Translator
def translate_to_english(text):
    try:
        # Sử dụng Google Translate qua Deep Translator
        translated = GoogleTranslator(source='auto', target='en').translate(text)
        return translated
    except Exception as e:
        print(f"Translation failed for: {text}, Error: {e}")
        return text  # Trả về văn bản gốc nếu dịch lỗi
map_data = data.ten_cong_viec.value_counts().to_frame().reset_index().drop(columns=["count"])
vectorized_func = np.vectorize(translate_to_english)
map_res = vectorized_func(map_data["ten_cong_viec"].to_numpy())

In [13]:
map_data["translated"] = map_res
map_data = map_data.set_index("ten_cong_viec")
map_dict = map_data["translated"].to_dict()

In [14]:
def map_translate_result(text):
    try:
        return map_dict[text]
    except:
        print("Error mapping")
        return ""

# 6. Áp dụng hàm vào cột "Job Title"
data['ten_cong_viec'] = data['ten_cong_viec'].apply(map_translate_result)

# 7. In kết quả
data['ten_cong_viec']

0      Viettel Digital Service (VDS) - Senior Java De...
1           Project Leader/ Team Leader (BrSE, Japanese)
2         Senior Java Developer (JLPT N2, Sign-on Bonus)
3      AI Development Engineer - Information Technolo...
4      Automation Tester - Information Technology Div...
                             ...
501                           Senior Front-End Developer
502                           Senior Fullstack Developer
503    [Urgent] SOFTWARE ENGINEER (C#, Prism Library ...
504            Mobile App Programming Engineer (Flutter)
505                                     Software testers
Name: ten_cong_viec, Length: 12231, dtype: object

## Cluster the jobs from job titles

In [15]:
# Reusing job group keywords for classification
job_groups = {
    "Management": ["manager", "lead", "coordinator", "scrum", "product owner","administrator","management"],
    "Software/Web/Mobile Development": ["programmer", "coder", "software","web","frontend","backend","game","development","fullstack","dev", "mobile", "ios", "android", "flutter", "react native"],
    "Data & AI": ["data", "ml", "machine learning", "big data", "scientist","ai engineer","ai technical"],
    "Business Analysis":["business analyst","business analysis","business system analyst"],
    "IT Solution & Consulting":["solution","consultant"],
    "QA & Testing": ["qa", "test", "testing", "automation","assurance"],
    "Infrastructure & DevOps": ["devops", "cloud", "system", "administrator", "infrastructure","architect"],
    "Cybersecurity": ["security", "cyber", "pen tester", "forensic", "vulnerability"],
    "Design & UI/UX": ["designer", "ui", "ux", "graphic", "product designer","2D","3D"],
    "Support": ["support", "helpdesk", "service desk"],
    "Other": []
}

# Classify jobs into groups based on keywords
def classify_job(title):
    title_lower = title.lower()
    matched_groups = []
    for group, keywords in job_groups.items():
        if any(keyword in title_lower for keyword in keywords):
            matched_groups.append(group)
    return matched_groups if matched_groups else ["Other"]

job_titles_sample = data["ten_cong_viec"]
# Apply classification to the sample titles
classified_jobs = {title: classify_job(title) for title in job_titles_sample}
data["nhom_cong_viec"] = classified_jobs

In [16]:
data["nhom_cong_viec"] = data["ten_cong_viec"].apply(classify_job)
data.nhom_cong_viec.explode().value_counts()

nhom_cong_viec
Software/Web/Mobile Development    6080
Management                         2039
Infrastructure & DevOps            1676
QA & Testing                       1309
Data & AI                          1206
Other                               666
Cybersecurity                       644
IT Solution & Consulting            607
Business Analysis                   573
Support                             368
Design & UI/UX                      230
Name: count, dtype: int64

In [17]:
data.head()

,ten_cong_viec,ten_cong_ty,muc_luong,dia_chi,ngay_dang,nganh_nghe,quy_mo_cong_ty,quoc_tich_cong_ty,nam_kinh_nghiem,cap_bac,...,loai_hop_dong,cong_nghe_su_dung,quy_trinh_phong_van,mo_ta_cong_viec,thong_tin_cong_ty,url,thoi_gian_hien_tai,url_cong_ty,so_luong_nhan_vien,nhom_cong_viec
0,Viettel Digital Service (VDS) - Senior Java De...,Viettel Group,"[0, 0]","[Tòa Keangnam Landmark 72 tầng, đường Phạm Hùn...",Đăng 3 ngày trước,"[Viễn Thông, Dịch vụ doanh nghiệp, Phần Mềm]",Lớn,[Vietnam],5.0,[Senior],...,[Fulltime],"[Java, SQL, Java Core]","[Vòng 1: Test IQ, chuyên môn và ngoại ngữ, Vòn...",Tổng Công ty Dịch vụ số Viettel - Viettel Digi...,Về chúng tôi\nTập đoàn Công nghiệp – Viễn thôn...,https://topdev.vn/viec-lam/viettel-digital-ser...,2024-12-03 21:28:28.210355,https://topdev.vn/vi/nha-tuyen-dung/viettel-gr...,"[1000, 2000000]",[Software/Web/Mobile Development]
1,"Project Leader/ Team Leader (BrSE, Japanese)",NEC Vietnam,"[0, 0]","[Lầu 9, Etown 3, 364 Cộng Hòa, Phường 13, Quận...",Đăng 2 ngày trước,[Phần Mềm],Vừa,[Japan],5.0,"[Trưởng phòng, Trưởng Nhóm, Senior]",...,[Fulltime],"[Japanese - N3, Japanese, BrSE, BSE Leader, Pr...",[Vòng 1: Interview with Hiring Managers],ONE OF THE TOP ICT JAPANESE COMPANIES IN VIETN...,Về chúng tôi\nNEC established its liaison offi...,https://topdev.vn/viec-lam/project-leader-team...,2024-12-03 21:28:28.210355,https://topdev.vn/nha-tuyen-dung/nec-vietnam-7...,"[100, 499]",[Management]
2,"Senior Java Developer (JLPT N2, Sign-on Bonus)",NEC Vietnam,"[0, 0]","[Lầu 9, Etown 3, 364 Cộng Hòa, Phường 13, Quận...",Đăng 5 ngày trước,[Phần Mềm],Vừa,[Japan],4.0,"[Trưởng Nhóm, Senior]",...,[Fulltime],"[Java, Japanese - N3, Japanese - N2, Java Core...",[],ONE OF THE TOP ICT JAPANESE COMPANIES IN VIETN...,Về chúng tôi\nNEC established its liaison offi...,https://topdev.vn/viec-lam/senior-java-develop...,2024-12-03 21:28:28.210355,https://topdev.vn/nha-tuyen-dung/nec-vietnam-7...,"[100, 499]",[Software/Web/Mobile Development]
3,AI Development Engineer - Information Technolo...,MBBANK,"[0, 0]","[MB Tower, số 18 Lê Văn Lương, Phường Trung Ho...",Đăng 19 giờ trước,[Ngân Hàng],Lớn,[Vietnam],2.0,"[Junior, Middle, Senior]",...,[Fulltime],"[Java, Python, Scala, AI, FastAPI]",[],"Trách nhiệm công việc\n Phát triển, ứng dụng, ...","Về chúng tôi\nĐược thành lập từ năm 1994, với ...",https://topdev.vn/viec-lam/ky-su-phat-trien-ai...,2024-12-03 21:28:28.210355,https://topdev.vn/nha-tuyen-dung/mbbank-94346?...,"[1000, 2000000]",[Software/Web/Mobile Development]
4,Automation Tester - Information Technology Div...,MBBANK,"[0, 0]","[MB Tower, số 18 Lê Văn Lương, Phường Trung Ho...",Đăng 19 giờ trước,[Ngân Hàng],Lớn,[Vietnam],2.0,"[Junior, Middle, Senior]",...,[Fulltime],"[Tester, Automation Tester, Mobile Tester, Web...",[],Trách nhiệm công việc\nXây dựng dụng cụ cho au...,"Về chúng tôi\nĐược thành lập từ năm 1994, với ...",https://topdev.vn/viec-lam/chuyen-vien-kiem-th...,2024-12-03 21:28:28.210355,https://topdev.vn/nha-tuyen-dung/mbbank-94346?...,"[1000, 2000000]",[QA & Testing]

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12231 entries, 0 to 505
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_cong_viec        12231 non-null  object
 1   ten_cong_ty          12231 non-null  object
 2   muc_luong            12231 non-null  object
 3   dia_chi              12231 non-null  object
 4   ngay_dang            12231 non-null  object
 5   nganh_nghe           12231 non-null  object
 6   quy_mo_cong_ty       12231 non-null  object
 7   quoc_tich_cong_ty    12231 non-null  object
 8   nam_kinh_nghiem      12231 non-null  float64
 9   cap_bac              12231 non-null  object
 10  loai_hinh            12231 non-null  object
 11  loai_hop_dong        12231 non-null  object
 12  cong_nghe_su_dung    12231 non-null  object
 13  quy_trinh_phong_van  12231 non-null  object
 14  mo_ta_cong_viec      12231 non-null  object
 15  thong_tin_cong_ty    12231 non-null  object
 16  url                  12231 non-null  object
 17  thoi_gian_hien_tai   12231 non-null  datetime64[ns]
 18  url_cong_ty          12231 non-null  object
 19  so_luong_nhan_vien   12231 non-null  object
 20  nhom_cong_viec       12231 non-null  object
dtypes: datetime64[ns](1), float64(1), object(19)
memory usage: 2.1+ MB

# Push to MongoDB Atlas (Cloud Database)

In [19]:
from IPython.display import display, Markdown
from pymongo.mongo_client import MongoClient
from bson.objectid import ObjectId

In [20]:
uri = "mongodb+srv://endgame:endgame@cluster0.rkdhc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri)

# Send a ping to confirm a successful connection
try:
    client.admin.command("ping")
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

db = client["udptdltm"]
collection = db["data"]

Pinged your deployment. You successfully connected to MongoDB!

> Check the len of the database before

In [21]:
object_ids = [doc["_id"] for doc in collection.find({}, {"_id": 1})]
len(object_ids)

12231

> Push to cloud

In [22]:
tmp = []
for i in range(data.shape[0]):
    tmp.append(data.iloc[i].to_dict())

collection.insert_many(tmp)

InsertManyResult([ObjectId('698182947cc0c08f6d06a10c'), ObjectId('698182947cc0c08f6d06a10d'), ObjectId('698182947cc0c08f6d06a10e'), ObjectId('698182947cc0c08f6d06a10f'), ObjectId('698182947cc0c08f6d06a110'), ObjectId('698182947cc0c08f6d06a111'), ObjectId('698182947cc0c08f6d06a112'), ObjectId('698182947cc0c08f6d06a113'), ObjectId('698182947cc0c08f6d06a114'), ObjectId('698182947cc0c08f6d06a115'), ObjectId('698182947cc0c08f6d06a116'), ObjectId('698182947cc0c08f6d06a117'), ObjectId('698182947cc0c08f6d06a118'), ObjectId('698182947cc0c08f6d06a119'), ObjectId('698182947cc0c08f6d06a11a'), ObjectId('698182947cc0c08f6d06a11b'), ObjectId('698182947cc0c08f6d06a11c'), ObjectId('698182947cc0c08f6d06a11d'), ObjectId('698182947cc0c08f6d06a11e'), ObjectId('698182947cc0c08f6d06a11f'), ObjectId('698182947cc0c08f6d06a120'), ObjectId('698182947cc0c08f6d06a121'), ObjectId('698182947cc0c08f6d06a122'), ObjectId('698182947cc0c08f6d06a123'), ObjectId('698182947cc0c08f6d06a124'), ObjectId('698182947cc0c08f6d06a125'), ObjectId('698182947cc0c08f6d06a126'), ObjectId('698182947cc0c08f6d06a127'), ObjectId('698182947cc0c08f6d06a128'), ObjectId('698182947cc0c08f6d06a129'), ObjectId('698182947cc0c08f6d06a12a'), ObjectId('698182947cc0c08f6d06a12b'), ObjectId('698182947cc0c08f6d06a12c'), ObjectId('698182947cc0c08f6d06a12d'), ObjectId('698182947cc0c08f6d06a12e'), ObjectId('698182947cc0c08f6d06a12f'), ObjectId('698182947cc0c08f6d06a130'), ObjectId('698182947cc0c08f6d06a131'), ObjectId('698182947cc0c08f6d06a132'), ObjectId('698182947cc0c08f6d06a133'), ObjectId('698182947cc0c08f6d06a134'), ObjectId('698182947cc0c08f6d06a135'), ObjectId('698182947cc0c08f6d06a136'), ObjectId('698182947cc0c08f6d06a137'), ObjectId('698182947cc0c08f6d06a138'), ObjectId('698182947cc0c08f6d06a139'), ObjectId('698182947cc0c08f6d06a13a'), ObjectId('698182947cc0c08f6d06a13b'), ObjectId('698182947cc0c08f6d06a13c'), ObjectId('698182947cc0c08f6d06a13d'), ObjectId('698182947cc0c08f6d06a13e'), ObjectId('698182947cc0c08f6d06a13f'), ObjectId('698182947cc0c08f6d06a140'), ObjectId('698182947cc0c08f6d06a141'), ObjectId('698182947cc0c08f6d06a142'), ObjectId('698182947cc0c08f6d06a143'), ObjectId('698182947cc0c08f6d06a144'), ObjectId('698182947cc0c08f6d06a145'), ObjectId('698182947cc0c08f6d06a146'), ObjectId('698182947cc0c08f6d06a147'), ObjectId('698182947cc0c08f6d06a148'), ObjectId('698182947cc0c08f6d06a149'), ObjectId('698182947cc0c08f6d06a14a'), ObjectId('698182947cc0c08f6d06a14b'), ObjectId('698182947cc0c08f6d06a14c'), ObjectId('698182947cc0c08f6d06a14d'), ObjectId('698182947cc0c08f6d06a14e'), ObjectId('698182947cc0c08f6d06a14f'), ObjectId('698182947cc0c08f6d06a150'), ObjectId('698182947cc0c08f6d06a151'), ObjectId('698182947cc0c08f6d06a152'), ObjectId('698182947cc0c08f6d06a153'), ObjectId('698182947cc0c08f6d06a154'), ObjectId('698182947cc0c08f6d06a155'), ObjectId('698182947cc0c08f6d06a156'), ObjectId('698182947cc0c08f6d06a157'), ObjectId('698182947cc0c08f6d06a158'), ObjectId('698182947cc0c08f6d06a159'), ObjectId('698182947cc0c08f6d06a15a'), ObjectId('698182947cc0c08f6d06a15b'), ObjectId('698182947cc0c08f6d06a15c'), ObjectId('698182947cc0c08f6d06a15d'), ObjectId('698182947cc0c08f6d06a15e'), ObjectId('698182947cc0c08f6d06a15f'), ObjectId('698182947cc0c08f6d06a160'), ObjectId('698182947cc0c08f6d06a161'), ObjectId('698182947cc0c08f6d06a162'), ObjectId('698182947cc0c08f6d06a163'), ObjectId('698182947cc0c08f6d06a164'), ObjectId('698182947cc0c08f6d06a165'), ObjectId('698182947cc0c08f6d06a166'), ObjectId('698182947cc0c08f6d06a167'), ObjectId('698182947cc0c08f6d06a168'), ObjectId('698182947cc0c08f6d06a169'), ObjectId('698182947cc0c08f6d06a16a'), ObjectId('698182947cc0c08f6d06a16b'), ObjectId('698182947cc0c08f6d06a16c'), ObjectId('698182947cc0c08f6d06a16d'), ObjectId('698182947cc0c08f6d06a16e'), ObjectId('698182947cc0c08f6d06a16f'), ObjectId('698182947cc0c08f6d06a170'), ObjectId('698182947cc0c08f6d06a171'), ObjectId('698182947cc0c08f6d06a172'), ObjectId('698182947cc0c08f6d06a173'), ObjectId('698182947cc0c08f6d06a174'), ObjectId('698182947cc0c08f6d06a175'), ObjectId('698182947cc0c08f6d06a176'), ObjectId('698182947cc0c08f6d06a177'), ObjectId('698182947cc0c08f6d06a178'), ObjectId('698182947cc0c08f6d06a179'), ObjectId('698182947cc0c08f6d06a17a'), ObjectId('698182947cc0c08f6d06a17b'), ObjectId('698182947cc0c08f6d06a17c'), ObjectId('698182947cc0c08f6d06a17d'), ObjectId('698182947cc0c08f6d06a17e'), ObjectId('698182947cc0c08f6d06a17f'), ObjectId('698182947cc0c08f6d06a180'), ObjectId('698182947cc0c08f6d06a181'), ObjectId('698182947cc0c08f6d06a182'), ObjectId('698182947cc0c08f6d06a183'), ObjectId('698182947cc0c08f6d06a184'), ObjectId('698182947cc0c08f6d06a185'), ObjectId('698182947cc0c08f6d06a186'), ObjectId('698182947cc0c08f6d06a187'), ObjectId('698182947cc0c08f6d06a188'), ObjectId('698182947cc0c08f6d06a189'), ObjectId('698182947cc0c08f6d06a18a'), ObjectId('698182947cc0c08f6d06a18b'), ObjectId('698182947cc0c08f6d06a18c'), ObjectId('698182947cc0c08f6d06a18d'), ObjectId('698182947cc0c08f6d06a18e'), ObjectId('698182947cc0c08f6d06a18f'), ObjectId('698182947cc0c08f6d06a190'), ObjectId('698182947cc0c08f6d06a191'), ObjectId('698182947cc0c08f6d06a192'), ObjectId('698182947cc0c08f6d06a193'), ObjectId('698182947cc0c08f6d06a194'), ObjectId('698182947cc0c08f6d06a195'), ObjectId('698182947cc0c08f6d06a196'), ObjectId('698182947cc0c08f6d06a197'), ObjectId('698182947cc0c08f6d06a198'), ObjectId('698182947cc0c08f6d06a199'), ObjectId('698182947cc0c08f6d06a19a'), ObjectId('698182947cc0c08f6d06a19b'), ObjectId('698182947cc0c08f6d06a19c'), ObjectId('698182947cc0c08f6d06a19d'), ObjectId('698182947cc0c08f6d06a19e'), ObjectId('698182947cc0c08f6d06a19f'), ObjectId('698182947cc0c08f6d06a1a0'), ObjectId('698182947cc0c08f6d06a1a1'), ObjectId('698182947cc0c08f6d06a1a2'), ObjectId('698182947cc0c08f6d06a1a3'), ObjectId('698182947cc0c08f6d06a1a4'), ObjectId('698182947cc0c08f6d06a1a5'), ObjectId('698182947cc0c08f6d06a1a6'), ObjectId('698182947cc0c08f6d06a1a7'), ObjectId('698182947cc0c08f6d06a1a8'), ObjectId('698182947cc0c08f6d06a1a9'), ObjectId('698182947cc0c08f6d06a1aa'), ObjectId('698182947cc0c08f6d06a1ab'), ObjectId('698182947cc0c08f6d06a1ac'), ObjectId('698182947cc0c08f6d06a1ad'), ObjectId('698182947cc0c08f6d06a1ae'), ObjectId('698182947cc0c08f6d06a1af'), ObjectId('698182947cc0c08f6d06a1b0'), ObjectId('698182947cc0c08f6d06a1b1'), ObjectId('698182947cc0c08f6d06a1b2'), ObjectId('698182947cc0c08f6d06a1b3'), ObjectId('698182947cc0c08f6d06a1b4'), ObjectId('698182947cc0c08f6d06a1b5'), ObjectId('698182947cc0c08f6d06a1b6'), ObjectId('698182947cc0c08f6d06a1b7'), ObjectId('698182947cc0c08f6d06a1b8'), ObjectId('698182947cc0c08f6d06a1b9'), ObjectId('698182947cc0c08f6d06a1ba'), ObjectId('698182947cc0c08f6d06a1bb'), ObjectId('698182947cc0c08f6d06a1bc'), ObjectId('698182947cc0c08f6d06a1bd'), ObjectId('698182947cc0c08f6d06a1be'), ObjectId('698182947cc0c08f6d06a1bf'), ObjectId('698182947cc0c08f6d06a1c0'), ObjectId('698182947cc0c08f6d06a1c1'), ObjectId('698182947cc0c08f6d06a1c2'), ObjectId('698182947cc0c08f6d06a1c3'), ObjectId('698182947cc0c08f6d06a1c4'), ObjectId('698182947cc0c08f6d06a1c5'), ObjectId('698182947cc0c08f6d06a1c6'), ObjectId('698182947cc0c08f6d06a1c7'), ObjectId('698182947cc0c08f6d06a1c8'), ObjectId('698182947cc0c08f6d06a1c9'), ObjectId('698182947cc0c08f6d06a1ca'), ObjectId('698182947cc0c08f6d06a1cb'), ObjectId('698182947cc0c08f6d06a1cc'), ObjectId('698182947cc0c08f6d06a1cd'), ObjectId('698182947cc0c08f6d06a1ce'), ObjectId('698182947cc0c08f6d06a1cf'), ObjectId('698182947cc0c08f6d06a1d0'), ObjectId('698182947cc0c08f6d06a1d1'), ObjectId('698182947cc0c08f6d06a1d2'), ObjectId('698182947cc0c08f6d06a1d3'), ObjectId('698182947cc0c08f6d06a1d4'), ObjectId('698182947cc0c08f6d06a1d5'), ObjectId('698182947cc0c08f6d06a1d6'), ObjectId('698182947cc0c08f6d06a1d7'), ObjectId('698182947cc0c08f6d06a1d8'), ObjectId('698182947cc0c08f6d06a1d9'), ObjectId('698182947cc0c08f6d06a1da'), ObjectId('698182947cc0c08f6d06a1db'), ObjectId('698182947cc0c08f6d06a1dc'), ObjectId('698182947cc0c08f6d06a1dd'), ObjectId('698182947cc0c08f6d06a1de'), ObjectId('698182947cc0c08f6d06a1df'), ObjectId('698182947cc0c08f6d06a1e0'), ObjectId('698182947cc0c08f6d06a1e1'), ObjectId('698182947cc0c08f6d06a1e2'), ObjectId('698182947cc0c08f6d06a1e3'), ObjectId('698182947cc0c08f6d06a1e4'), ObjectId('698182947cc0c08f6d06a1e5'), ObjectId('698182947cc0c08f6d06a1e6'), ObjectId('698182947cc0c08f6d06a1e7'), ObjectId('698182947cc0c08f6d06a1e8'), ObjectId('698182947cc0c08f6d06a1e9'), ObjectId('698182947cc0c08f6d06a1ea'), ObjectId('698182947cc0c08f6d06a1eb'), ObjectId('698182947cc0c08f6d06a1ec'), ObjectId('698182947cc0c08f6d06a1ed'), ObjectId('698182947cc0c08f6d06a1ee'), ObjectId('698182947cc0c08f6d06a1ef'), ObjectId('698182947cc0c08f6d06a1f0'), ObjectId('698182947cc0c08f6d06a1f1'), ObjectId('698182947cc0c08f6d06a1f2'), ObjectId('698182947cc0c08f6d06a1f3'), ObjectId('698182947cc0c08f6d06a1f4'), ObjectId('698182947cc0c08f6d06a1f5'), ObjectId('698182947cc0c08f6d06a1f6'), ObjectId('698182947cc0c08f6d06a1f7'), ObjectId('698182947cc0c08f6d06a1f8'), ObjectId('698182947cc0c08f6d06a1f9'), ObjectId('698182947cc0c08f6d06a1fa'), ObjectId('698182947cc0c08f6d06a1fb'), ObjectId('698182947cc0c08f6d06a1fc'), ObjectId('698182947cc0c08f6d06a1fd'), ObjectId('698182947cc0c08f6d06a1fe'), ObjectId('698182947cc0c08f6d06a1ff'), ObjectId('698182947cc0c08f6d06a200'), ObjectId('698182947cc0c08f6d06a201'), ObjectId('698182947cc0c08f6d06a202'), ObjectId('698182947cc0c08f6d06a203'), ObjectId('698182947cc0c08f6d06a204'), ObjectId('698182947cc0c08f6d06a205'), ObjectId('698182947cc0c08f6d06a206'), ObjectId('698182947cc0c08f6d06a207'), ObjectId('698182947cc0c08f6d06a208'), ObjectId('698182947cc0c08f6d06a209'), ObjectId('698182947cc0c08f6d06a20a'), ObjectId('698182947cc0c08f6d06a20b'), ObjectId('698182947cc0c08f6d06a20c'), ObjectId('698182947cc0c08f6d06a20d'), ObjectId('698182947cc0c08f6d06a20e'), ObjectId('698182947cc0c08f6d06a20f'), ObjectId('698182947cc0c08f6d06a210'), ObjectId('698182947cc0c08f6d06a211'), ObjectId('698182947cc0c08f6d06a212'), ObjectId('698182947cc0c08f6d06a213'), ObjectId('698182947cc0c08f6d06a214'), ObjectId('698182947cc0c08f6d06a215'), ObjectId('698182947cc0c08f6d06a216'), ObjectId('698182947cc0c08f6d06a217'), ObjectId('698182947cc0c08f6d06a218'), ObjectId('698182947cc0c08f6d06a219'), ObjectId('698182947cc0c08f6d06a21a'), ObjectId('698182947cc0c08f6d06a21b'), ObjectId('698182947cc0c08f6d06a21c'), ObjectId('698182947cc0c08f6d06a21d'), ObjectId('698182947cc0c08f6d06a21e'), ObjectId('698182947cc0c08f6d06a21f'), ObjectId('698182947cc0c08f6d06a220'), ObjectId('698182947cc0c08f6d06a221'), ObjectId('698182947cc0c08f6d06a222'), ObjectId('698182947cc0c08f6d06a223'), ObjectId('698182947cc0c08f6d06a224'), ObjectId('698182947cc0c08f6d06a225'), ObjectId('698182947cc0c08f6d06a226'), ObjectId('698182947cc0c08f6d06a227'), ObjectId('698182947cc0c08f6d06a228'), ObjectId('698182947cc0c08f6d06a229'), ObjectId('698182947cc0c08f6d06a22a'), ObjectId('698182947cc0c08f6d06a22b'), ObjectId('698182947cc0c08f6d06a22c'), ObjectId('698182947cc0c08f6d06a22d'), ObjectId('698182947cc0c08f6d06a22e'), ObjectId('698182947cc0c08f6d06a22f'), ObjectId('698182947cc0c08f6d06a230'), ObjectId('698182947cc0c08f6d06a231'), ObjectId('698182947cc0c08f6d06a232'), ObjectId('698182947cc0c08f6d06a233'), ObjectId('698182947cc0c08f6d06a234'), ObjectId('698182947cc0c08f6d06a235'), ObjectId('698182947cc0c08f6d06a236'), ObjectId('698182947cc0c08f6d06a237'), ObjectId('698182947cc0c08f6d06a238'), ObjectId('698182947cc0c08f6d06a239'), ObjectId('698182947cc0c08f6d06a23a'), ObjectId('698182947cc0c08f6d06a23b'), ObjectId('698182947cc0c08f6d06a23c'), ObjectId('698182947cc0c08f6d06a23d'), ObjectId('698182947cc0c08f6d06a23e'), ObjectId('698182947cc0c08f6d06a23f'), ObjectId('698182947cc0c08f6d06a240'), ObjectId('698182947cc0c08f6d06a241'), ObjectId('698182947cc0c08f6d06a242'), ObjectId('698182947cc0c08f6d06a243'), ObjectId('698182947cc0c08f6d06a244'), ObjectId('698182947cc0c08f6d06a245'), ObjectId('698182947cc0c08f6d06a246'), ObjectId('698182947cc0c08f6d06a247'), ObjectId('698182947cc0c08f6d06a248'), ObjectId('698182947cc0c08f6d06a249'), ObjectId('698182947cc0c08f6d06a24a'), ObjectId('698182947cc0c08f6d06a24b'), ObjectId('698182947cc0c08f6d06a24c'), ObjectId('698182947cc0c08f6d06a24d'), ObjectId('698182947cc0c08f6d06a24e'), ObjectId('698182947cc0c08f6d06a24f'), ObjectId('698182947cc0c08f6d06a250'), ObjectId('698182947cc0c08f6d06a251'), ObjectId('698182947cc0c08f6d06a252'), ObjectId('698182947cc0c08f6d06a253'), ObjectId('698182947cc0c08f6d06a254'), ObjectId('698182947cc0c08f6d06a255'), ObjectId('698182947cc0c08f6d06a256'), ObjectId('698182947cc0c08f6d06a257'), ObjectId('698182947cc0c08f6d06a258'), ObjectId('698182947cc0c08f6d06a259'), ObjectId('698182947cc0c08f6d06a25a'), ObjectId('698182947cc0c08f6d06a25b'), ObjectId('698182947cc0c08f6d06a25c'), ObjectId('698182947cc0c08f6d06a25d'), ObjectId('698182947cc0c08f6d06a25e'), ObjectId('698182947cc0c08f6d06a25f'), ObjectId('698182947cc0c08f6d06a260'), ObjectId('698182947cc0c08f6d06a261'), ObjectId('698182947cc0c08f6d06a262'), ObjectId('698182947cc0c08f6d06a263'), ObjectId('698182947cc0c08f6d06a264'), ObjectId('698182947cc0c08f6d06a265'), ObjectId('698182947cc0c08f6d06a266'), ObjectId('698182947cc0c08f6d06a267'), ObjectId('698182947cc0c08f6d06a268'), ObjectId('698182947cc0c08f6d06a269'), ObjectId('698182947cc0c08f6d06a26a'), ObjectId('698182947cc0c08f6d06a26b'), ObjectId('698182947cc0c08f6d06a26c'), ObjectId('698182947cc0c08f6d06a26d'), ObjectId('698182947cc0c08f6d06a26e'), ObjectId('698182947cc0c08f6d06a26f'), ObjectId('698182947cc0c08f6d06a270'), ObjectId('698182947cc0c08f6d06a271'), ObjectId('698182947cc0c08f6d06a272'), ObjectId('698182947cc0c08f6d06a273'), ObjectId('698182947cc0c08f6d06a274'), ObjectId('698182947cc0c08f6d06a275'), ObjectId('698182947cc0c08f6d06a276'), ObjectId('698182947cc0c08f6d06a277'), ObjectId('698182947cc0c08f6d06a278'), ObjectId('698182947cc0c08f6d06a279'), ObjectId('698182947cc0c08f6d06a27a'), ObjectId('698182947cc0c08f6d06a27b'), ObjectId('698182947cc0c08f6d06a27c'), ObjectId('698182947cc0c08f6d06a27d'), ObjectId('698182947cc0c08f6d06a27e'), ObjectId('698182947cc0c08f6d06a27f'), ObjectId('698182947cc0c08f6d06a280'), ObjectId('698182947cc0c08f6d06a281'), ObjectId('698182947cc0c08f6d06a282'), ObjectId('698182947cc0c08f6d06a283'), ObjectId('698182947cc0c08f6d06a284'), ObjectId('698182947cc0c08f6d06a285'), ObjectId('698182947cc0c08f6d06a286'), ObjectId('698182947cc0c08f6d06a287'), ObjectId('698182947cc0c08f6d06a288'), ObjectId('698182947cc0c08f6d06a289'), ObjectId('698182947cc0c08f6d06a28a'), ObjectId('698182947cc0c08f6d06a28b'), ObjectId('698182947cc0c08f6d06a28c'), ObjectId('698182947cc0c08f6d06a28d'), ObjectId('698182947cc0c08f6d06a28e'), ObjectId('698182947cc0c08f6d06a28f'), ObjectId('698182947cc0c08f6d06a290'), ObjectId('698182947cc0c08f6d06a291'), ObjectId('698182947cc0c08f6d06a292'), ObjectId('698182947cc0c08f6d06a293'), ObjectId('698182947cc0c08f6d06a294'), ObjectId('698182947cc0c08f6d06a295'), ObjectId('698182947cc0c08f6d06a296'), ObjectId('698182947cc0c08f6d06a297'), ObjectId('698182947cc0c08f6d06a298'), ObjectId('698182947cc0c08f6d06a299'), ObjectId('698182947cc0c08f6d06a29a'), ObjectId('698182947cc0c08f6d06a29b'), ObjectId('698182947cc0c08f6d06a29c'), ObjectId('698182947cc0c08f6d06a29d'), ObjectId('698182947cc0c08f6d06a29e'), ObjectId('698182947cc0c08f6d06a29f'), ObjectId('698182947cc0c08f6d06a2a0'), ObjectId('698182947cc0c08f6d06a2a1'), ObjectId('698182947cc0c08f6d06a2a2'), ObjectId('698182947cc0c08f6d06a2a3'), ObjectId('698182947cc0c08f6d06a2a4'), ObjectId('698182947cc0c08f6d06a2a5'), ObjectId('698182947cc0c08f6d06a2a6'), ObjectId('698182947cc0c08f6d06a2a7'), ObjectId('698182947cc0c08f6d06a2a8'), ObjectId('698182947cc0c08f6d06a2a9'), ObjectId('698182947cc0c08f6d06a2aa'), ObjectId('698182947cc0c08f6d06a2ab'), ObjectId('698182947cc0c08f6d06a2ac'), ObjectId('698182947cc0c08f6d06a2ad'), ObjectId('698182947cc0c08f6d06a2ae'), ObjectId('698182947cc0c08f6d06a2af'), ObjectId('698182947cc0c08f6d06a2b0'), ObjectId('698182947cc0c08f6d06a2b1'), ObjectId('698182947cc0c08f6d06a2b2'), ObjectId('698182947cc0c08f6d06a2b3'), ObjectId('698182947cc0c08f6d06a2b4'), ObjectId('698182947cc0c08f6d06a2b5'), ObjectId('698182947cc0c08f6d06a2b6'), ObjectId('698182947cc0c08f6d06a2b7'), ObjectId('698182947cc0c08f6d06a2b8'), ObjectId('698182947cc0c08f6d06a2b9'), ObjectId('698182947cc0c08f6d06a2ba'), ObjectId('698182947cc0c08f6d06a2bb'), ObjectId('698182947cc0c08f6d06a2bc'), ObjectId('698182947cc0c08f6d06a2bd'), ObjectId('698182947cc0c08f6d06a2be'), ObjectId('698182947cc0c08f6d06a2bf'), ObjectId('698182947cc0c08f6d06a2c0'), ObjectId('698182947cc0c08f6d06a2c1'), ObjectId('698182947cc0c08f6d06a2c2'), ObjectId('698182947cc0c08f6d06a2c3'), ObjectId('698182947cc0c08f6d06a2c4'), ObjectId('698182947cc0c08f6d06a2c5'), ObjectId('698182947cc0c08f6d06a2c6'), ObjectId('698182947cc0c08f6d06a2c7'), ObjectId('698182947cc0c08f6d06a2c8'), ObjectId('698182947cc0c08f6d06a2c9'), ObjectId('698182947cc0c08f6d06a2ca'), ObjectId('698182947cc0c08f6d06a2cb'), ObjectId('698182947cc0c08f6d06a2cc'), ObjectId('698182947cc0c08f6d06a2cd'), ObjectId('698182947cc0c08f6d06a2ce'), ObjectId('698182947cc0c08f6d06a2cf'), ObjectId('698182947cc0c08f6d06a2d0'), ObjectId('698182947cc0c08f6d06a2d1'), ObjectId('698182947cc0c08f6d06a2d2'), ObjectId('698182947cc0c08f6d06a2d3'), ObjectId('698182947cc0c08f6d06a2d4'), ObjectId('698182947cc0c08f6d06a2d5'), ObjectId('698182947cc0c08f6d06a2d6'), ObjectId('698182947cc0c08f6d06a2d7'), ObjectId('698182947cc0c08f6d06a2d8'), ObjectId('698182947cc0c08f6d06a2d9'), ObjectId('698182947cc0c08f6d06a2da'), ObjectId('698182947cc0c08f6d06a2db'), ObjectId('698182947cc0c08f6d06a2dc'), ObjectId('698182947cc0c08f6d06a2dd'), ObjectId('698182947cc0c08f6d06a2de'), ObjectId('698182947cc0c08f6d06a2df'), ObjectId('698182947cc0c08f6d06a2e0'), ObjectId('698182947cc0c08f6d06a2e1'), ObjectId('698182947cc0c08f6d06a2e2'), ObjectId('698182947cc0c08f6d06a2e3'), ObjectId('698182947cc0c08f6d06a2e4'), ObjectId('698182947cc0c08f6d06a2e5'), ObjectId('698182947cc0c08f6d06a2e6'), ObjectId('698182947cc0c08f6d06a2e7'), ObjectId('698182947cc0c08f6d06a2e8'), ObjectId('698182947cc0c08f6d06a2e9'), ObjectId('698182947cc0c08f6d06a2ea'), ObjectId('698182947cc0c08f6d06a2eb'), ObjectId('698182947cc0c08f6d06a2ec'), ObjectId('698182947cc0c08f6d06a2ed'), ObjectId('698182947cc0c08f6d06a2ee'), ObjectId('698182947cc0c08f6d06a2ef'), ObjectId('698182947cc0c08f6d06a2f0'), ObjectId('698182947cc0c08f6d06a2f1'), ObjectId('698182947cc0c08f6d06a2f2'), ObjectId('698182947cc0c08f6d06a2f3'), ObjectId('698182947cc0c08f6d06a2f4'), ObjectId('698182947cc0c08f6d06a2f5'), ObjectId('698182947cc0c08f6d06a2f6'), ObjectId('698182947cc0c08f6d06a2f7'), ObjectId('698182947cc0c08f6d06a2f8'), ObjectId('698182947cc0c08f6d06a2f9'), ObjectId('698182947cc0c08f6d06a2fa'), ObjectId('698182947cc0c08f6d06a2fb'), ObjectId('698182947cc0c08f6d06a2fc'), ObjectId('698182947cc0c08f6d06a2fd'), ObjectId('698182947cc0c08f6d06a2fe'), ObjectId('698182947cc0c08f6d06a2ff'), ObjectId('698182947cc0c08f6d06a300'), ObjectId('698182947cc0c08f6d06a301'), ObjectId('698182947cc0c08f6d06a302'), ObjectId('698182947cc0c08f6d06a303'), ObjectId('698182947cc0c08f6d06a304'), ObjectId('698182947cc0c08f6d06a305'), ObjectId('698182947cc0c08f6d06a306'), ObjectId('698182947cc0c08f6d06a307'), ObjectId('698182947cc0c08f6d06a308'), ObjectId('698182947cc0c08f6d06a309'), ObjectId('698182947cc0c08f6d06a30a'), ObjectId('698182947cc0c08f6d06a30b'), ObjectId('698182947cc0c08f6d06a30c'), ObjectId('698182947cc0c08f6d06a30d'), ObjectId('698182947cc0c08f6d06a30e'), ObjectId('698182947cc0c08f6d06a30f'), ObjectId('698182947cc0c08f6d06a310'), ObjectId('698182947cc0c08f6d06a311'), ObjectId('698182947cc0c08f6d06a312'), ObjectId('698182947cc0c08f6d06a313'), ObjectId('698182947cc0c08f6d06a314'), ObjectId('698182947cc0c08f6d06a315'), ObjectId('698182947cc0c08f6d06a316'), ObjectId('698182947cc0c08f6d06a317'), ObjectId('698182947cc0c08f6d06a318'), ObjectId('698182947cc0c08f6d06a3

> Check the len of the database after

In [23]:
object_ids = [doc["_id"] for doc in collection.find({}, {"_id": 1})]
len(object_ids)

24462

In [24]:
collection.distinct("thoi_gian_hien_tai")

[datetime.datetime(2024, 10, 29, 23, 49, 40, 410000),
 datetime.datetime(2024, 10, 30, 21, 12, 27, 898000),
 datetime.datetime(2024, 10, 31, 22, 31, 43, 598000),
 datetime.datetime(2024, 11, 1, 18, 57, 33, 986000),
 datetime.datetime(2024, 11, 2, 21, 31, 49, 226000),
 datetime.datetime(2024, 11, 3, 21, 38, 30),
 datetime.datetime(2024, 11, 4, 22, 16, 5, 607000),
 datetime.datetime(2024, 11, 5, 21, 36, 12, 594000),
 datetime.datetime(2024, 11, 6, 22, 21, 3, 196000),
 datetime.datetime(2024, 11, 7, 21, 16, 27, 26000),
 datetime.datetime(2024, 11, 8, 21, 29, 37, 990000),
 datetime.datetime(2024, 11, 9, 22, 2, 25, 48000),
 datetime.datetime(2024, 11, 10, 20, 31, 45, 149000),
 datetime.datetime(2024, 11, 11, 14, 20, 13, 537000),
 datetime.datetime(2024, 11, 12, 21, 37, 52, 656000),
 datetime.datetime(2024, 11, 13, 13, 39, 32, 143000),
 datetime.datetime(2024, 11, 14, 14, 45, 15, 444000),
 datetime.datetime(2024, 11, 15, 21, 20, 17, 292000),
 datetime.datetime(2024, 11, 16, 20, 54, 43, 495000),
 datetime.datetime(2024, 11, 17, 21, 55, 19, 72000),
 datetime.datetime(2024, 11, 18, 22, 27, 2, 468000),
 datetime.datetime(2024, 11, 19, 21, 47, 19, 572000),
 datetime.datetime(2024, 11, 20, 21, 33, 28, 6000),
 datetime.datetime(2024, 11, 21, 21, 37, 42, 229000),
 datetime.datetime(2024, 11, 22, 22, 20, 46, 415000),
 datetime.datetime(2024, 11, 23, 21, 26, 46, 48000),
 datetime.datetime(2024, 11, 24, 23, 46, 54, 600000),
 datetime.datetime(2024, 11, 25, 22, 23, 41, 205000),
 datetime.datetime(2024, 11, 26, 22, 19, 4, 541000),
 datetime.datetime(2024, 11, 27, 21, 15, 26, 441000),
 datetime.datetime(2024, 11, 28, 20, 55, 17, 541000),
 datetime.datetime(2024, 11, 29, 21, 57, 1, 42000),
 datetime.datetime(2024, 11, 30, 23, 58, 53, 998000),
 datetime.datetime(2024, 12, 1, 20, 32, 28, 498000),
 datetime.datetime(2024, 12, 2, 22, 24, 5, 29000),
 datetime.datetime(2024, 12, 3, 21, 28, 28, 210000),
 datetime.datetime(2024, 12, 4, 20, 53, 14, 194000),
 datetime.datetime(2024, 12, 5, 20, 26, 25, 371000),
 datetime.datetime(2024, 12, 6, 14, 31, 57, 937000)]

In [25]:
df = data.drop_duplicates(subset="url", keep="first").reset_index(drop=True)
df.to_csv("processed_data.csv", index=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_cong_viec        537 non-null    object
 1   ten_cong_ty          537 non-null    object
 2   muc_luong            537 non-null    object
 3   dia_chi              537 non-null    object
 4   ngay_dang            537 non-null    object
 5   nganh_nghe           537 non-null    object
 6   quy_mo_cong_ty       537 non-null    object
 7   quoc_tich_cong_ty    537 non-null    object
 8   nam_kinh_nghiem      537 non-null    float64
 9   cap_bac              537 non-null    object
 10  loai_hinh            537 non-null    object
 11  loai_hop_dong        537 non-null    object
 12  cong_nghe_su_dung    537 non-null    object
 13  quy_trinh_phong_van  537 non-null    object
 14  mo_ta_cong_viec      537 non-null    object
 15  thong_tin_cong_ty    537 non-null    object
 16  url                  537 non-null    object
 17  thoi_gian_hien_tai   537 non-null    datetime64[ns]
 18  url_cong_ty          537 non-null    object
 19  so_luong_nhan_vien   537 non-null    object
 20  nhom_cong_viec       537 non-null    object
dtypes: datetime64[ns](1), float64(1), object(19)
memory usage: 88.2+ KB